select 'CREATE INDEX CCCS_'||
        substr(TABLE_NAME,1,17)||
        '_NVL_IND ON '||owner||'.'||TABLE_NAME||' (NVL(MIF_VALUE,''CCCS'')) TABLESPACE INDX;'
  FROM DBA_TABLES
  WHERE TABLE_NAME IN ('MGT_COMMUNICATION',
'MGT_STUDENT_PERIOD_DEFINITION',
'MGT_YEAR_TYPE_DEFINTION',
'MRT_APPLICANT_NEED',
'MRT_AWARD_BY_AID_YEAR',
'MRT_AWARD_BY_PERSON',
'MRT_FINAID_APPLICATION1',
'MRT_FINAID_APPLICATION2',
'MRT_FINAID_BUDGET_COMPONENT',
'MRT_FINAID_FUND',
'MST_ACADEMIC_OUTCOME',
'MST_ACADEMIC_OUTCOME',
'MST_ACADEMIC_STANDING',
'MST_ADDRESS',
'MST_ADMINISTRATOR',
'MST_ADMISSIONS_APPLICATION',
'MST_ADMISSIONS_ATTRIBUTE',
'MST_ADMISSIONS_COHORT',
'MST_ADMISSIONS_DECISION',
'MST_ADMISSIONS_RATING',
'MST_ADMISSIONS_REQUIREMENT',
'MST_ADMISSIONS_SOURCE',
'MST_ADVISOR',
'MST_BASE_STUDENT',
'MST_CONTACT',
'MST_COURSE_CATALOG',
'MST_COURSE_OFFERING',
'MST_COURSE_SUPPLEMENTAL',
'MST_ENROLLMENT',
'MST_FACULTY_DEPT_COLLEGE',
'MST_GENERAL_STUDENT',
'MST_GEOGRAPHIC_REGION',
'MST_GEOGRAPHIC_REGION_INST',
'MST_GPA',
'MST_HOLD',
'MST_INSTITUTION',
'MST_INSTITUTION_CHARACTERISTIC',
'MST_INSTITUTION_DEMOGRAPHIC',
'MST_INSTRUCTIONAL_ASSIGNMENT',
'MST_INTEREST',
'MST_MEETING_TIME',
'MST_MEETING_TIME',
'MST_OUTCOME_HONOR',
'MST_PERSON',
'MST_PREVIOUS_EDUCATION',
'MST_RACE',
'MST_RECRUITMENT_ATTRIBUTE',
'MST_RECRUITMENT_COHORT',
'MST_RECRUITMENT_INFORMATION',
'MST_RECRUITMENT_SOURCE',
'MST_SECONDARY_SCHOOL_SUBJECT',
'MST_SPORT',
'MST_STUDENT_ACTIVITY',
'MST_STUDENT_ATTRIBUTE',
'MST_STUDENT_CLASSIFICATION',
'MST_STUDENT_CLASSIFICATION',
'MST_STUDENT_COHORT',
'MST_STUDENT_COURSE ',
'MST_STUDENT_COURSE_ATTRIBUTE',
'MST_STUDENT_COURSE_ATTRIBUTE',
'MST_STUDENT_COURSE_GRADE_CHG',
'MST_STUDENT_COURSE_GRADE_CHG',
'MST_TELEPHONE',
'MST_VISA',
'MTT_AR_DEPOSIT',
'WDT_WAREHOUSE_ENTITY')
order by 1;

select 'CREATE INDEX CCCS_'||
        substr(TABLE_NAME,1,16)||
        '_NVL_IND2 ON '||owner||'.'||TABLE_NAME||' (NVL(MIF_VALUE,'' '')) TABLESPACE INDX;'
  FROM DBA_TABLES
  WHERE TABLE_NAME IN ('MST_COURSE_CATALOG',
                       'MST_COURSE_OFFERING',
                       'MST_COURSE_SUPPLEMENTAL',
                       'MST_RECRUITMENT_INFORMATION',
                       'MST_STUDENT_COURSE',
                       'MTT_AR_DEPOSIT')
order by 1;




select 'alter INDEX CCCS_'||
        substr(TABLE_NAME,1,17)||
        '_NVL_IND compute statistics;'
  FROM DBA_TABLES
  WHERE TABLE_NAME IN ('MGT_COMMUNICATION',
'MGT_STUDENT_PERIOD_DEFINITION',
'MGT_YEAR_TYPE_DEFINTION',
'MRT_APPLICANT_NEED',
'MRT_AWARD_BY_AID_YEAR',
'MRT_AWARD_BY_PERSON',
'MRT_FINAID_APPLICATION1',
'MRT_FINAID_APPLICATION2',
'MRT_FINAID_BUDGET_COMPONENT',
'MRT_FINAID_FUND',
'MST_ACADEMIC_OUTCOME',
'MST_ACADEMIC_OUTCOME',
'MST_ACADEMIC_STANDING',
'MST_ADDRESS',
'MST_ADMINISTRATOR',
'MST_ADMISSIONS_APPLICATION',
'MST_ADMISSIONS_ATTRIBUTE',
'MST_ADMISSIONS_COHORT',
'MST_ADMISSIONS_DECISION',
'MST_ADMISSIONS_RATING',
'MST_ADMISSIONS_REQUIREMENT',
'MST_ADMISSIONS_SOURCE',
'MST_ADVISOR',
'MST_BASE_STUDENT',
'MST_CONTACT',
'MST_COURSE_CATALOG',
'MST_COURSE_OFFERING',
'MST_COURSE_SUPPLEMENTAL',
'MST_ENROLLMENT',
'MST_FACULTY_DEPT_COLLEGE',
'MST_GENERAL_STUDENT',
'MST_GEOGRAPHIC_REGION',
'MST_GEOGRAPHIC_REGION_INST',
'MST_GPA',
'MST_HOLD',
'MST_INSTITUTION',
'MST_INSTITUTION_CHARACTERISTIC',
'MST_INSTITUTION_DEMOGRAPHIC',
'MST_INSTRUCTIONAL_ASSIGNMENT',
'MST_INTEREST',
'MST_MEETING_TIME',
'MST_MEETING_TIME',
'MST_OUTCOME_HONOR',
'MST_PERSON',
'MST_PREVIOUS_EDUCATION',
'MST_RACE',
'MST_RECRUITMENT_ATTRIBUTE',
'MST_RECRUITMENT_COHORT',
'MST_RECRUITMENT_INFORMATION',
'MST_RECRUITMENT_SOURCE',
'MST_SECONDARY_SCHOOL_SUBJECT',
'MST_SPORT',
'MST_STUDENT_ACTIVITY',
'MST_STUDENT_ATTRIBUTE',
'MST_STUDENT_CLASSIFICATION',
'MST_STUDENT_CLASSIFICATION',
'MST_STUDENT_COHORT',
'MST_STUDENT_COURSE ',
'MST_STUDENT_COURSE_ATTRIBUTE',
'MST_STUDENT_COURSE_ATTRIBUTE',
'MST_STUDENT_COURSE_GRADE_CHG',
'MST_STUDENT_COURSE_GRADE_CHG',
'MST_TELEPHONE',
'MST_VISA',
'MTT_AR_DEPOSIT',
'WDT_WAREHOUSE_ENTITY');




select 'alter INDEX CCCS_'||
        substr(TABLE_NAME,1,16)||
        '_NVL_IND2 compute statistics;'
  FROM DBA_TABLES
  WHERE TABLE_NAME IN ('MST_COURSE_CATALOG',
                       'MST_COURSE_OFFERING',
                       'MST_COURSE_SUPPLEMENTAL',
                       'MST_RECRUITMENT_INFORMATION',
                       'MST_STUDENT_COURSE',
                       'MTT_AR_DEPOSIT');
                       
                       
                       
create index cccs_stvvtyp_non_res on SATURN.STVVTYP("STVVTYP_NON_RES_IND") tablespace indx;                       