/* As EDWMGR */
drop index edwmgr.wft_finaid_award_aprd_01;
drop index edwmgr.wft_finaid_award_aprd_02;
drop index edwmgr.wft_finaid_award_aprd_03;
drop index edwmgr.wft_finaid_award_aprd_05;
drop index edwmgr.wft_finaid_award_aprd_06;
drop index edwmgr.wft_finaid_award_aprd_07;
drop index edwmgr.wft_finaid_award_aprd_08;
drop index WFT_FINAID_APPL_INDEX_01;
drop index WFT_FINAID_APPL_INDEX_02;
drop index WFT_FINAID_APPL_INDEX_03;
drop index WFT_FINAID_APPL_INDEX_04;
drop index WFT_FINAID_APPL_INDEX_05;
drop index WFT_FINAID_APPL_INDEX_06;
drop index WFT_FINAID_APPL_INDEX_07;
drop index WFT_FINAID_APPL_INDEX_08;
drop index WFT_FINAID_APPL_INDEX_09;
drop index WFT_FINAID_APPL_INDEX_10;
drop index WFT_FINAID_APPL_INDEX_11;
drop index WFT_FINAID_APPL_INDEX_12;
drop index WFT_FINAID_AWARD_APRD_04;
drop index WFT_FINAID_AWARD_AIDY_01;
drop index WFT_FINAID_AWARD_AIDY_02;
drop index WFT_FINAID_AWARD_AIDY_03;
drop index WFT_FINAID_AWARD_AIDY_04;
drop index WFT_FINAID_AWARD_AIDY_05;
drop index WFT_FINAID_AWARD_AIDY_06;
drop index WFT_FINAID_AWARD_AIDY_07; 

create index CCCS_wft_finaid_award_aprd_01 ON EDWMGR.wft_finaid_award_acad_period(multi_source_key);
create index CCCS_wft_finaid_award_aprd_02 ON EDWMGR.wft_finaid_award_acad_period(financial_aid_year_key);
create index CCCS_wft_finaid_award_aprd_03 ON EDWMGR.wft_finaid_award_acad_period(academic_time_key);
create index CCCS_wft_finaid_award_aprd_05 ON EDWMGR.wft_finaid_award_acad_period(demographic_key);
create index CCCS_wft_finaid_award_aprd_06 ON EDWMGR.wft_finaid_award_acad_period(financial_aid_fund_key);
create index CCCS_wft_finaid_award_aprd_07 ON EDWMGR.wft_finaid_award_acad_period(financial_aid_status_key);
create index CCCS_wft_finaid_award_aprd_08 ON EDWMGR.wft_finaid_award_acad_period(financial_aid_fund_status_key);
create index cccs_WFT_FINAID_APPL_INDEX_01 on edwmgr.WFT_FINAID_APPLICATION(multi_source_key);
create index cccs_WFT_FINAID_APPL_INDEX_02 on edwmgr.WFT_FINAID_APPLICATION(fINANCIAL_AID_YEAR_KEY);
create index cccs_WFT_FINAID_APPL_INDEX_03 on edwmgr.WFT_FINAID_APPLICATION(FINANCIAL_AID_PERIOD_KEY);
create index cccs_WFT_FINAID_APPL_INDEX_04 on edwmgr.WFT_FINAID_APPLICATION(PERSON_UID);
create index cccs_WFT_FINAID_APPL_INDEX_05 on edwmgr.WFT_FINAID_APPLICATION(DEMOGRAPHIC_KEY);
create index cccs_WFT_FINAID_APPL_INDEX_06 on edwmgr.WFT_FINAID_APPLICATION(FINANCIAL_AID_STATUS_KEY);
create index cccs_WFT_FINAID_APPL_INDEX_07 on edwmgr.WFT_FINAID_APPLICATION(FINANCIAL_AID_BUDGET_GRP_KEY);
create index cccs_WFT_FINAID_APPL_INDEX_08 on edwmgr.WFT_FINAID_APPLICATION(FINANCIAL_AID_PACKAGE_GRP_KEY);
create index cccs_WFT_FINAID_APPL_INDEX_09 on edwmgr.WFT_FINAID_APPLICATION(PACKAGING_COMPLETE_IND);
create index cccs_WFT_FINAID_APPL_INDEX_10 on edwmgr.WFT_FINAID_APPLICATION(OTHER_RESOURCE_IND);
create index cccs_WFT_FINAID_APPL_INDEX_11 on edwmgr.WFT_FINAID_APPLICATION(FM_BATCH_LOCK_IND);
create index cccs_WFT_FINAID_APPL_INDEX_12 on edwmgr.WFT_FINAID_APPLICATION(IM_BATCH_LOCK_IND);
create index cccs_WFT_FINAID_AWARD_AIDY_01 on edwmgr.WFT_FINAID_AWARD_AID_YEAR(MULTI_SOURCE_KEY);
create index cccs_WFT_FINAID_AWARD_AIDY_02 on edwmgr.WFT_FINAID_AWARD_AID_YEAR(FINANCIAL_AID_YEAR_KEY);
--create index cccs_WFT_FINAID_AWARD_AIDY_03 on edwmgr.WFT_FINAID_AWARD_AID_YEAR(
create index cccs_WFT_FINAID_AWARD_AIDY_04 on edwmgr.WFT_FINAID_AWARD_AID_YEAR(DEMOGRAPHIC_KEY);
create index cccs_WFT_FINAID_AWARD_AIDY_05 on edwmgr.WFT_FINAID_AWARD_AID_YEAR(FINANCIAL_AID_FUND_KEY);
create index cccs_WFT_FINAID_AWARD_AIDY_06 on edwmgr.WFT_FINAID_AWARD_AID_YEAR(FINANCIAL_AID_STATUS_KEY);
create index cccs_WFT_FINAID_AWARD_AIDY_07 on edwmgr.WFT_FINAID_AWARD_AID_YEAR(FINANCIAL_AID_FUND_STATUS_KEY);


/* As IA_ADMIN */
UPDATE mgbindx SET mgbindx_indextype = ' ' WHERE lower(mgbindx_indexname) =  'wft_finaid_award_aprd_01';
UPDATE mgbindx SET mgbindx_indextype = ' ' WHERE lower(mgbindx_indexname) =  'wft_finaid_award_aprd_02';
UPDATE mgbindx SET mgbindx_indextype = ' ' WHERE lower(mgbindx_indexname) =  'wft_finaid_award_aprd_03';
UPDATE mgbindx SET mgbindx_indextype = ' ' WHERE lower(mgbindx_indexname) =  'wft_finaid_award_aprd_05';
UPDATE mgbindx SET mgbindx_indextype = ' ' WHERE lower(mgbindx_indexname) =  'wft_finaid_award_aprd_06';
UPDATE mgbindx SET mgbindx_indextype = ' ' WHERE lower(mgbindx_indexname) =  'wft_finaid_award_aprd_07';
UPDATE mgbindx SET mgbindx_indextype = ' ' WHERE lower(mgbindx_indexname) =  'wft_finaid_award_aprd_08';
UPDATE mgbindx SET mgbindx_indextype = ' ' WHERE upper(mgbindx_indexname) =  'WFT_FINAID_APPL_INDEX_01';
UPDATE mgbindx SET mgbindx_indextype = ' ' WHERE upper(mgbindx_indexname) =  'WFT_FINAID_APPL_INDEX_02';
UPDATE mgbindx SET mgbindx_indextype = ' ' WHERE upper(mgbindx_indexname) =  'WFT_FINAID_APPL_INDEX_03';
UPDATE mgbindx SET mgbindx_indextype = ' ' WHERE upper(mgbindx_indexname) =  'WFT_FINAID_APPL_INDEX_04';
UPDATE mgbindx SET mgbindx_indextype = ' ' WHERE upper(mgbindx_indexname) =  'WFT_FINAID_APPL_INDEX_05';
UPDATE mgbindx SET mgbindx_indextype = ' ' WHERE upper(mgbindx_indexname) =  'WFT_FINAID_APPL_INDEX_06';
UPDATE mgbindx SET mgbindx_indextype = ' ' WHERE upper(mgbindx_indexname) =  'WFT_FINAID_APPL_INDEX_07';
UPDATE mgbindx SET mgbindx_indextype = ' ' WHERE upper(mgbindx_indexname) =  'WFT_FINAID_APPL_INDEX_08';
UPDATE mgbindx SET mgbindx_indextype = ' ' WHERE upper(mgbindx_indexname) =  'WFT_FINAID_APPL_INDEX_09';
UPDATE mgbindx SET mgbindx_indextype = ' ' WHERE upper(mgbindx_indexname) =  'WFT_FINAID_APPL_INDEX_10';
UPDATE mgbindx SET mgbindx_indextype = ' ' WHERE upper(mgbindx_indexname) =  'WFT_FINAID_APPL_INDEX_11';
UPDATE mgbindx SET mgbindx_indextype = ' ' WHERE upper(mgbindx_indexname) =  'WFT_FINAID_APPL_INDEX_12';
UPDATE mgbindx SET mgbindx_indextype = ' ' WHERE upper(mgbindx_indexname) =  'WFT_FINAID_AWARD_APRD_04';
UPDATE mgbindx SET mgbindx_indextype = ' ' WHERE upper(mgbindx_indexname) =  'WFT_FINAID_AWARD_AIDY_01';
UPDATE mgbindx SET mgbindx_indextype = ' ' WHERE upper(mgbindx_indexname) =  'WFT_FINAID_AWARD_AIDY_02';
UPDATE mgbindx SET mgbindx_indextype = ' ' WHERE upper(mgbindx_indexname) =  'WFT_FINAID_AWARD_AIDY_03';
UPDATE mgbindx SET mgbindx_indextype = ' ' WHERE upper(mgbindx_indexname) =  'WFT_FINAID_AWARD_AIDY_04';
UPDATE mgbindx SET mgbindx_indextype = ' ' WHERE upper(mgbindx_indexname) =  'WFT_FINAID_AWARD_AIDY_05';
UPDATE mgbindx SET mgbindx_indextype = ' ' WHERE upper(mgbindx_indexname) =  'WFT_FINAID_AWARD_AIDY_06';
UPDATE mgbindx SET mgbindx_indextype = ' ' WHERE upper(mgbindx_indexname) =  'WFT_FINAID_AWARD_AIDY_07';