drop materialized view "ODSMGR"."CHG_STUDENT_COURSE_ATTR_V";
commit;



  CREATE MATERIALIZED VIEW "ODSMGR"."CHG_STUDENT_COURSE_ATTR_V" ("PERSON_UID", "COURSE_REFERENCE_NUMBER", "CHANGE_PROCESS_ID", "CHANGE_ACTIVITY_DATE","ACADEMIC_PERIOD")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPMENT" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH COMPLETE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS select "PERSON_UID","COURSE_REFERENCE_NUMBER","CHANGE_PROCESS_ID","CHANGE_ACTIVITY_DATE","ACADEMIC_PERIOD" from edwstg.CHG_STUDENT_COURSE_ATTR;

   COMMENT ON MATERIALIZED VIEW "ODSMGR"."CHG_STUDENT_COURSE_ATTR_V"  IS 'snapshot table for snapshot ODSMGR.CHG_STUDENT_COURSE_ATTR_V';

  CREATE OR REPLACE PUBLIC SYNONYM "CHG_STUDENT_COURSE_ATTR_V" FOR "ODSMGR"."CHG_STUDENT_COURSE_ATTR_V";