/*
select odsmgr.f_get_pidm('S01473923') from dual;
select * from mst_student_cohort where person_uid = 1349176; --2014 & 2015
select * from wdt_warehouse_entity where banner_pidm = 1941845 and user_attribute_01 = 'PCC';
select * from wtt_student_cohort_input where e_academic_period is not null;


/*PROD*/
select count(*) from wtt_student_cohort_clean where academic_period = s_academic_period
and academic_period = e_academic_period
and academic_period = cs_academic_period
and academic_period = ce_academic_period; --170,743 (all), 2330, 93, 40, 0
/*TEST*/
select count(*) from wtt_student_cohort_clean where academic_period = s_academic_period --2330
and academic_period = e_academic_period --93
and academic_period = cs_academic_period --40
and academic_period = ce_academic_period; --0


select distinct academic_year, academic_period_start, academic_period_end, cohort_start_academic_period, cohort_end_academic_period, mif_value
  from mst_student_cohort
  where academic_year >= '2009'
  order by academic_year, academic_period_start;




select ACADEMIC_PERIOD_WV,S_ACADEMIC_PERIOD_WV,E_ACADEMIC_PERIOD_WV, CS_ACADEMIC_PERIOD_WV, C_ACADEMIC_PERIOD_WV   from wtt_student_cohort_clean;
select CATE_USER_ATTRIBUTE_01_WV, count(*)  from wtt_student_cohort_clean group by CATE_USER_ATTRIBUTE_01_WV;
select * from WDT_COHORT;
select user_attribute_01, count(*) from WDT_ACADEMIC_TIME group by user_attribute_01;
select * from wdt_warehouse_entity where warehouse_entity_uid = '20975500'; --pidm: 1941845
select * from mst_student_cohort where person_uid = 1941845;

select * from mst_person where person_uid = 1941845;
select odsmgr.f_get_pidm('S02065388') from dual;
*/
select count(1) from table(edw_student_extr.f_get_student_cohort('2009','L',sysdate));

SELECT count(*)
/* WTT_STUDENT_COHORT_CLEAN.INOUTGRP1, WDT_MULTI_SOURCE.OUTGRP1 */
 
FROM
  "WTT_STUDENT_COHORT_CLEAN"  "WTT_STUDENT_COHORT_CLEAN",
"EDWMGR"."WDT_MULTI_SOURCE"  "WDT_MULTI_SOURCE", --170743,
"EDWMGR"."WDT_ACADEMIC_TIME"  "WDT_ACADEMIC_TIME" --170743
,
"EDWMGR"."WDT_ACADEMIC_TIME"  "WDT_ACADEMIC_TIME2" /*,  --drop down to 48K
"EDWMGR"."WDT_ACADEMIC_TIME"  "WDT_ACADEMIC_TIME3",
"EDWMGR"."WDT_DEMOGRAPHIC"  "WDT_DEMOGRAPHIC",
"EDWMGR"."WDT_COHORT"  "WDT_COHORT",
"EDWMGR"."WDT_ACADEMIC_TIME"  "WDT_ACADEMIC_TIME4",
"EDWMGR"."WDT_ACADEMIC_TIME"  "WDT_ACADEMIC_TIME5" */
  WHERE 
  ( "WDT_MULTI_SOURCE"."MULTI_SOURCE" = "WTT_STUDENT_COHORT_CLEAN"."MULTI_SOURCE_WV" ) AND
  ( "WDT_MULTI_SOURCE"."PROCESS_GROUP" = "WTT_STUDENT_COHORT_CLEAN"."PROCESS_GROUP_WV" )  AND
  ( "WDT_MULTI_SOURCE"."ADMINISTRATIVE_GROUP" = "WTT_STUDENT_COHORT_CLEAN"."ADMINISTRATIVE_GROUP_WV" )  AND
  ( "WDT_MULTI_SOURCE"."USER_ATTRIBUTE_01" = "WTT_STUDENT_COHORT_CLEAN"."MSRC_USER_ATTRIBUTE_01_WV" )  AND
  ( "WDT_MULTI_SOURCE"."USER_ATTRIBUTE_02" = "WTT_STUDENT_COHORT_CLEAN"."MSRC_USER_ATTRIBUTE_02_WV" )  AND
  ( "WDT_MULTI_SOURCE"."USER_ATTRIBUTE_03" = "WTT_STUDENT_COHORT_CLEAN"."MSRC_USER_ATTRIBUTE_03_WV" )  AND
  ( "WDT_MULTI_SOURCE"."USER_ATTRIBUTE_04" = "WTT_STUDENT_COHORT_CLEAN"."MSRC_USER_ATTRIBUTE_04_WV" )  AND
  ( "WDT_MULTI_SOURCE"."USER_ATTRIBUTE_05" = "WTT_STUDENT_COHORT_CLEAN"."MSRC_USER_ATTRIBUTE_05_WV" )  AND
  ( "WDT_ACADEMIC_TIME"."ACADEMIC_PERIOD" = "WTT_STUDENT_COHORT_CLEAN"."ACADEMIC_PERIOD_WV" )  AND
  ( "WDT_ACADEMIC_TIME"."ACADEMIC_YEAR" = "WTT_STUDENT_COHORT_CLEAN"."ACADEMIC_YEAR_WV" )  AND
  ( "WDT_ACADEMIC_TIME"."USER_ATTRIBUTE_01" = "WTT_STUDENT_COHORT_CLEAN"."ATIM_USER_ATTRIBUTE_01_WV" )  AND
  ( "WDT_ACADEMIC_TIME"."USER_ATTRIBUTE_02" = "WTT_STUDENT_COHORT_CLEAN"."ATIM_USER_ATTRIBUTE_02_WV" )  AND
  ( "WDT_ACADEMIC_TIME"."USER_ATTRIBUTE_03" = "WTT_STUDENT_COHORT_CLEAN"."ATIM_USER_ATTRIBUTE_03_WV" )  AND
  ( "WDT_ACADEMIC_TIME"."USER_ATTRIBUTE_04" = "WTT_STUDENT_COHORT_CLEAN"."ATIM_USER_ATTRIBUTE_04_WV" )  AND
  ( "WDT_ACADEMIC_TIME"."USER_ATTRIBUTE_05" = "WTT_STUDENT_COHORT_CLEAN"."ATIM_USER_ATTRIBUTE_05_WV" )  AND
  ( "WDT_ACADEMIC_TIME2"."ACADEMIC_PERIOD" = "WTT_STUDENT_COHORT_CLEAN"."S_ACADEMIC_PERIOD_WV" )  AND
  ( "WDT_ACADEMIC_TIME2"."ACADEMIC_YEAR" = "WTT_STUDENT_COHORT_CLEAN"."S_ACADEMIC_YEAR_WV" )  AND
  ( "WDT_ACADEMIC_TIME2"."USER_ATTRIBUTE_01" = "WTT_STUDENT_COHORT_CLEAN"."ATMS_USER_ATTRIBUTE_01_WV" )  AND
  ( "WDT_ACADEMIC_TIME2"."USER_ATTRIBUTE_02" = "WTT_STUDENT_COHORT_CLEAN"."ATMS_USER_ATTRIBUTE_02_WV" )  AND
  ( "WDT_ACADEMIC_TIME2"."USER_ATTRIBUTE_03" = "WTT_STUDENT_COHORT_CLEAN"."ATMS_USER_ATTRIBUTE_03_WV" )  AND
  ( "WDT_ACADEMIC_TIME2"."USER_ATTRIBUTE_04" = "WTT_STUDENT_COHORT_CLEAN"."ATMS_USER_ATTRIBUTE_04_WV" )  AND
  ( "WDT_ACADEMIC_TIME2"."USER_ATTRIBUTE_05" = "WTT_STUDENT_COHORT_CLEAN"."ATMS_USER_ATTRIBUTE_05_WV" )/*  AND
  ( "WDT_ACADEMIC_TIME3"."ACADEMIC_PERIOD" = "WTT_STUDENT_COHORT_CLEAN"."E_ACADEMIC_PERIOD_WV" )  AND
  ( "WDT_ACADEMIC_TIME3"."ACADEMIC_YEAR" = "WTT_STUDENT_COHORT_CLEAN"."E_ACADEMIC_YEAR_WV" )  AND
  ( "WDT_ACADEMIC_TIME3"."USER_ATTRIBUTE_01" = "WTT_STUDENT_COHORT_CLEAN"."ATME_USER_ATTRIBUTE_01_WV" )  AND
  ( "WDT_ACADEMIC_TIME3"."USER_ATTRIBUTE_02" = "WTT_STUDENT_COHORT_CLEAN"."ATME_USER_ATTRIBUTE_02_WV" )  AND
  ( "WDT_ACADEMIC_TIME3"."USER_ATTRIBUTE_03" = "WTT_STUDENT_COHORT_CLEAN"."ATME_USER_ATTRIBUTE_03_WV" )  AND
  ( "WDT_ACADEMIC_TIME3"."USER_ATTRIBUTE_04" = "WTT_STUDENT_COHORT_CLEAN"."ATME_USER_ATTRIBUTE_04_WV" )  AND
  ( "WDT_ACADEMIC_TIME3"."USER_ATTRIBUTE_05" = "WTT_STUDENT_COHORT_CLEAN"."ATME_USER_ATTRIBUTE_05_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."GENDER" = "WTT_STUDENT_COHORT_CLEAN"."GENDER_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."ETHNICITY_CATEGORY" = "WTT_STUDENT_COHORT_CLEAN"."ETHNICITY_CATEGORY_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."HISPANIC_LATINO_ETHNICITY_IND" = "WTT_STUDENT_COHORT_CLEAN"."HISPANIC_LATINO_ETHN_IND_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."ASIAN_IND" = "WTT_STUDENT_COHORT_CLEAN"."ASIAN_IND_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."NATIVE_AMERICAN_OR_ALASKAN_IND" = "WTT_STUDENT_COHORT_CLEAN"."NATIVE_AMER_OR_ALASKAN_IND_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."BLACK_OR_AFRICAN_IND" = "WTT_STUDENT_COHORT_CLEAN"."BLACK_OR_AFRICAN_IND_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."PACIFIC_ISLANDER_IND" = "WTT_STUDENT_COHORT_CLEAN"."PACIFIC_ISLANDER_IND_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."WHITE_IND" = "WTT_STUDENT_COHORT_CLEAN"."WHITE_IND_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."TWO_OR_MORE_IND" = "WTT_STUDENT_COHORT_CLEAN"."TWO_OR_MORE_IND_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."NON_RESIDENT_IND" = "WTT_STUDENT_COHORT_CLEAN"."NON_RESIDENT_IND_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."RACE_ETHNICITY_UNKNOWN_IND" = "WTT_STUDENT_COHORT_CLEAN"."RACE_ETHNICITY_UNKNOWN_IND_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."RACE_ETHNICITY_CONFIRM_IND" = "WTT_STUDENT_COHORT_CLEAN"."RACE_ETHNICITY_CONFIRM_IND_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."MINORITY_IND" = "WTT_STUDENT_COHORT_CLEAN"."MINORITY_IND_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."ETHNICITY" = "WTT_STUDENT_COHORT_CLEAN"."ETHNICITY_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."DECEASED_IND" = "WTT_STUDENT_COHORT_CLEAN"."DECEASED_IND_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."CITIZENSHIP_IND" = "WTT_STUDENT_COHORT_CLEAN"."CITIZENSHIP_IND_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."CITIZENSHIP_TYPE" = "WTT_STUDENT_COHORT_CLEAN"."CITIZENSHIP_TYPE_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."VISA_TYPE" = "WTT_STUDENT_COHORT_CLEAN"."VISA_TYPE_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."NATION_OF_CITIZENSHIP" = "WTT_STUDENT_COHORT_CLEAN"."NATION_OF_CITIZENSHIP_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."NATION_OF_BIRTH" = "WTT_STUDENT_COHORT_CLEAN"."NATION_OF_BIRTH_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."PRIMARY_DISABILITY" = "WTT_STUDENT_COHORT_CLEAN"."PRIMARY_DISABILITY_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."LEGACY" = "WTT_STUDENT_COHORT_CLEAN"."LEGACY_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."MARITAL_STATUS" = "WTT_STUDENT_COHORT_CLEAN"."MARITAL_STATUS_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."RELIGION" = "WTT_STUDENT_COHORT_CLEAN"."RELIGION_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."VETERAN_TYPE" = "WTT_STUDENT_COHORT_CLEAN"."VETERAN_TYPE_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."VETERAN_CATEGORY" = "WTT_STUDENT_COHORT_CLEAN"."VETERAN_CATEGORY_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."USER_ATTRIBUTE_01" = "WTT_STUDENT_COHORT_CLEAN"."DEMO_USER_ATTRIBUTE_01_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."USER_ATTRIBUTE_02" = "WTT_STUDENT_COHORT_CLEAN"."DEMO_USER_ATTRIBUTE_02_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."USER_ATTRIBUTE_03" = "WTT_STUDENT_COHORT_CLEAN"."DEMO_USER_ATTRIBUTE_03_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."USER_ATTRIBUTE_04" = "WTT_STUDENT_COHORT_CLEAN"."DEMO_USER_ATTRIBUTE_04_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."USER_ATTRIBUTE_05" = "WTT_STUDENT_COHORT_CLEAN"."DEMO_USER_ATTRIBUTE_05_WV" )  AND
  ( "WDT_COHORT"."COHORT" = "WTT_STUDENT_COHORT_CLEAN"."COHORT_WV" )  AND
  ( "WDT_COHORT"."COHORT_REPORT_IND" = "WTT_STUDENT_COHORT_CLEAN"."COHORT_REPORT_IND_WV" )  AND
  ( "WDT_COHORT"."COHORT_INACTIVE_REASON" = "WTT_STUDENT_COHORT_CLEAN"."COHORT_INACTIVE_REASON_WV" )  AND
  ( "WDT_COHORT"."USER_ATTRIBUTE_01" = "WTT_STUDENT_COHORT_CLEAN"."CHRT_USER_ATTRIBUTE_01_WV" )  AND
  ( "WDT_COHORT"."USER_ATTRIBUTE_02" = "WTT_STUDENT_COHORT_CLEAN"."CHRT_USER_ATTRIBUTE_02_WV" )  AND
  ( "WDT_COHORT"."USER_ATTRIBUTE_03" = "WTT_STUDENT_COHORT_CLEAN"."CHRT_USER_ATTRIBUTE_03_WV" )  AND
  ( "WDT_COHORT"."USER_ATTRIBUTE_04" = "WTT_STUDENT_COHORT_CLEAN"."CHRT_USER_ATTRIBUTE_04_WV" )  AND
  ( "WDT_COHORT"."USER_ATTRIBUTE_05" = "WTT_STUDENT_COHORT_CLEAN"."CHRT_USER_ATTRIBUTE_05_WV" )  AND
  ( "WDT_ACADEMIC_TIME4"."ACADEMIC_PERIOD" = "WTT_STUDENT_COHORT_CLEAN"."CS_ACADEMIC_PERIOD_WV" )  AND
  ( "WDT_ACADEMIC_TIME4"."ACADEMIC_YEAR" = "WTT_STUDENT_COHORT_CLEAN"."CS_ACADEMIC_YEAR_WV" )  AND
  ( "WDT_ACADEMIC_TIME4"."USER_ATTRIBUTE_01" = "WTT_STUDENT_COHORT_CLEAN"."CATS_USER_ATTRIBUTE_01_WV" )  AND
  ( "WDT_ACADEMIC_TIME4"."USER_ATTRIBUTE_02" = "WTT_STUDENT_COHORT_CLEAN"."CATS_USER_ATTRIBUTE_02_WV" )  AND
  ( "WDT_ACADEMIC_TIME4"."USER_ATTRIBUTE_03" = "WTT_STUDENT_COHORT_CLEAN"."CATS_USER_ATTRIBUTE_03_WV" )  AND
  ( "WDT_ACADEMIC_TIME4"."USER_ATTRIBUTE_04" = "WTT_STUDENT_COHORT_CLEAN"."CATS_USER_ATTRIBUTE_04_WV" )  AND
  ( "WDT_ACADEMIC_TIME4"."USER_ATTRIBUTE_05" = "WTT_STUDENT_COHORT_CLEAN"."CATS_USER_ATTRIBUTE_05_WV" )  AND
  ( "WDT_ACADEMIC_TIME5"."ACADEMIC_PERIOD" = "WTT_STUDENT_COHORT_CLEAN"."CE_ACADEMIC_PERIOD_WV" )  AND
  ( "WDT_ACADEMIC_TIME5"."ACADEMIC_YEAR" = "WTT_STUDENT_COHORT_CLEAN"."CE_ACADEMIC_YEAR_WV" )  AND
  --( "WDT_ACADEMIC_TIME5"."USER_ATTRIBUTE_01" = "WTT_STUDENT_COHORT_CLEAN"."CATE_USER_ATTRIBUTE_01_WV" )  AND
  ( "WDT_ACADEMIC_TIME5"."USER_ATTRIBUTE_02" = "WTT_STUDENT_COHORT_CLEAN"."CATE_USER_ATTRIBUTE_02_WV" )  AND
  ( "WDT_ACADEMIC_TIME5"."USER_ATTRIBUTE_03" = "WTT_STUDENT_COHORT_CLEAN"."CATE_USER_ATTRIBUTE_03_WV" )  AND
  ( "WDT_ACADEMIC_TIME5"."USER_ATTRIBUTE_04" = "WTT_STUDENT_COHORT_CLEAN"."CATE_USER_ATTRIBUTE_04_WV" )  AND
  ( "WDT_ACADEMIC_TIME5"."USER_ATTRIBUTE_05" = "WTT_STUDENT_COHORT_CLEAN"."CATE_USER_ATTRIBUTE_05_WV" ); */
  ;
  
  /* Bryan ran this late Friday -- why did these values load to test? How? why not to PROD?  YOu tried 2014 on friday, right? */
  /* Is this because of cartesianed wdt_academic_period stuff in test ? */
  select distinct academic_period, user_attribute_01 from wdt_academic_time
  where academic_time_key in (
  select distinct academic_time_key
    from wft_student_cohort)
    and academic_period between '200910' and '201530'
    order by academic_period desc, user_attribute_01;