SELECT
    'SHATCKN' BANNER_FORM,
    mgkfunc.f_get_person_info(SFRSTCR_PIDM, 'ID') id_number,
    mgkfunc.f_get_person_info(SFRSTCR_PIDM, 'L') last_name,
    mgkfunc.f_get_person_info(SFRSTCR_PIDM, 'F') first_name,
    SFRSTCR_PIDM PERSON_UID,
    STVTERM_ACYR_CODE ACADEMIC_YEAR,
    STVACYR_DESC ACADEMIC_YEAR_DESC,
    SFRSTCR_TERM_CODE ACADEMIC_PERIOD,
    STVTERM_DESC ACADEMIC_PERIOD_DESC,
    SFRSTCR_PTRM_CODE SUB_ACADEMIC_PERIOD,
    (
      SELECT
        STVPTRM_DESC
      FROM
        STVPTRM
      WHERE
        STVPTRM_CODE = SFRSTCR_PTRM_CODE
    )
    SUB_ACADEMIC_PERIOD_DESC,
    SSBSECT_SUBJ_CODE
    || SSBSECT_CRSE_NUMB COURSE_IDENTIFICATION,
    SSBSECT_SUBJ_CODE SUBJECT,
    STVSUBJ_DESC SUBJECT_DESC,
    SSBSECT_CRSE_NUMB COURSE_NUMBER,
    SSBSECT_SEQ_NUMB COURSE_SECTION_NUMBER,
    
    SFRSTCR_CRN COURSE_REFERENCE_NUMBER,
    SFRSTCR_REG_SEQ COURSE_SEQ_NO,
    DECODE(SFRSTCR_PIDM, NULL, 'Y','N') INSTITUTION_COURSE_IND,
    DECODE(SFRSTCR_PIDM, NULL, 'N','Y') IN_PROGRESS_COURSE_IND,
    DECODE(SFRSTCR_PIDM, NULL, 'Y','N') TRANSFER_COURSE_IND,
    SFRSTCR_RSTS_CODE REGISTRATION_STATUS,
    STVRSTS_INCL_SECT_ENRL COURSE_REGISTER_IND,
--    NVL(SSBSECT_CRSE_TITLE, SCBCRSE_TITLE) COURSE_TITLE_SHORT,
    SFRSTCR_GRDE_CODE FINAL_GRADE,
    DECODE(SFRSTCR_GRDE_DATE, NULL, 'N', 'Y') FINAL_GRADE_ROLL_IND,
    SSBSECT_CAMP_CODE course_campus, 
    SFRSTCR_VPDI_CODE MIF_VALUE,
    SUBSTR(GOKODSF.F_GET_DESC(SFRSTCR_VPDI_CODE, SFRSTCR_VPDI_CODE, 'GTVVPDI')
    ,1,30) MIF_DESC
FROM
    STVCAMP,
    STVSUBJ,
    STVACYR,
    STVTERM,
    SHRGRDE,
    SCBCRSE,
    SSBSECT,
    STVRSTS,
    SFRSTCR a
  WHERE
    SFRSTCR_VPDI_CODE    = SSBSECT_VPDI_CODE
  AND SFRSTCR_GRDE_DATE IS NULL
  AND SFRSTCR_TERM_CODE  = SSBSECT_TERM_CODE
  AND SFRSTCR_CRN        = SSBSECT_CRN
  AND SSBSECT_SUBJ_CODE  = SCBCRSE_SUBJ_CODE
  AND SSBSECT_CRSE_NUMB  = SCBCRSE_CRSE_NUMB
  AND SCBCRSE_EFF_TERM   =
    (
      SELECT
        MAX (X.SCBCRSE_EFF_TERM)
      FROM
        SCBCRSE X
      WHERE
        X.SCBCRSE_SUBJ_CODE   = SSBSECT_SUBJ_CODE
      AND X.SCBCRSE_CRSE_NUMB = SSBSECT_CRSE_NUMB
      AND X.SCBCRSE_EFF_TERM <= SFRSTCR_TERM_CODE
    )
  AND STVTERM_CODE      = SFRSTCR_TERM_CODE
  AND STVACYR_CODE      = STVTERM_ACYR_CODE
  AND STVSUBJ_CODE      = SSBSECT_SUBJ_CODE
  AND STVCAMP_CODE      = SFRSTCR_CAMP_CODE
  AND SHRGRDE.ROWID(+)  = SOKODSF. F_GET_SHRGRDE_ROWID (SFRSTCR_VPDI_CODE,
    SFRSTCR_GRDE_CODE, SFRSTCR_LEVL_CODE, SFRSTCR_TERM_CODE)
  AND STVRSTS_CODE(+)   = SFRSTCR_RSTS_CODE
  and sfrstcr_term_code >= '200910'
  and sfrstcr_vpdi_code in ('ACC', 'CCA', 'CCCS', 'CCD', 'CNCC', 'FRCC', 'LCC', 'MCC', 'OJC', 'NJC', 'PCC', 'PPCC', 'RRCC', 'TSJC')
  and exists (
    select 'x' 
      FROM
    SHRTCKN
  WHERE
  a.sfrstcr_pidm = shrtckn_pidm
  and a.sfrstcr_term_code = shrtckn_term_code
  and a.sfrstcr_crn = shrtckn_crn
  and a.sfrstcr_vpdi_code = shrtckn_vpdi_code)
--vpdi filter 



union all  
  --history
 SELECT
    'SFAALST/SFASLST' BANNER_FORM,
    mgkfunc.f_get_person_info(SHRTCKN_PIDM, 'ID') id_number,
    mgkfunc.f_get_person_info(SHRTCKN_PIDM, 'L') last_name,
    mgkfunc.f_get_person_info(SHRTCKN_PIDM, 'F') first_name,
    SHRTCKN_PIDM PERSON_UID,
    STVTERM_ACYR_CODE ACADEMIC_YEAR,
    STVACYR_DESC ACADEMIC_YEAR_DESC,
    SHRTCKN_TERM_CODE ACADEMIC_PERIOD,
    STVTERM_DESC ACADEMIC_PERIOD_DESC,
    SHRTCKN_PTRM_CODE SUB_ACADEMIC_PERIOD,
    (
      SELECT
        STVPTRM_DESC
      FROM
        STVPTRM
      WHERE
        STVPTRM_CODE = SHRTCKN_PTRM_CODE
    )
    SUB_ACADEMIC_PERIOD_DESC,
    SHRTCKN_SUBJ_CODE
    || SHRTCKN_CRSE_NUMB COURSE_IDENTIFICATION,
    SHRTCKN_SUBJ_CODE SUBJECT,
    STVSUBJ_DESC SUBJECT_DESC,
    SHRTCKN_CRSE_NUMB COURSE_NUMBER,
    SHRTCKN_SEQ_NUMB COURSE_SECTION_NUMBER,
    SHRTCKN_CRN COURSE_REFERENCE_NUMBER,
    SHRTCKN_SEQ_NO COURSE_SEQ_NO,
    CAST('Y' AS VARCHAR2(1)) INSTITUTION_COURSE_IND,
    CAST('N' AS VARCHAR2(1)) IN_PROGRESS_COURSE_IND,
    CAST('N' AS VARCHAR2(1)) TRANSFER_COURSE_IND,
    SFRSTCR_RSTS_CODE REGISTRATION_STATUS,
    NVL(STVRSTS_INCL_SECT_ENRL,'Y') COURSE_REGISTER_IND,
    SHRTCKG_GRDE_CODE_FINAL FINAL_GRADE,
    CAST('Y' AS VARCHAR2(1)) FINAL_GRADE_ROLL_IND,
    SHRTCKN_CAMP_CODE COURSE_CAMPUS,
    SHRTCKN_VPDI_CODE MIF_VALUE,
    SUBSTR(GOKODSF.F_GET_DESC(SHRTCKN_VPDI_CODE, SHRTCKN_VPDI_CODE, 'GTVVPDI')
    ,1,30) MIF_DESC
  FROM
    SHRTCKN,
    SHRTCKG,
    SFRSTCR,
    SHRTCKL,
    SHRGRDE,
    SSBSECT,
    STVRSTS,
    STVTERM,
    STVACYR,
    STVSUBJ,
    STVLEVL
  WHERE
    SHRTCKN_VPDI_CODE          = SFRSTCR_VPDI_CODE(+)
  AND SHRTCKN_VPDI_CODE        = SSBSECT_VPDI_CODE(+)
  AND SHRTCKN_VPDI_CODE        = SHRTCKL_VPDI_CODE
  AND SHRTCKN_TERM_CODE        = SFRSTCR_TERM_CODE (+)
  AND SHRTCKN_CRN              = SFRSTCR_CRN (+)
  AND SHRTCKN_PIDM             = SFRSTCR_PIDM (+)
  AND SFRSTCR_RSTS_CODE        = STVRSTS_CODE (+)
  AND SHRTCKN_TERM_CODE        = SSBSECT_TERM_CODE (+)
  AND SHRTCKN_CRN              = SSBSECT_CRN (+)
  AND SHRTCKN_PIDM             = SHRTCKL_PIDM
  AND SHRTCKN_TERM_CODE        = SHRTCKL_TERM_CODE
  AND SHRTCKN_SEQ_NO           = SHRTCKL_TCKN_SEQ_NO
  AND SHRTCKL_PRIMARY_LEVL_IND = 'Y'
  AND STVTERM_CODE             = SHRTCKN_TERM_CODE
  AND STVACYR_CODE             = STVTERM_ACYR_CODE
  AND STVSUBJ_CODE             = SHRTCKN_SUBJ_CODE
  AND STVLEVL_CODE             = SHRTCKL_LEVL_CODE
  AND SHRTCKG.ROWID            = SOKODSF.F_GET_SHRTCKG_ROWID (SHRTCKN_VPDI_CODE
    , SHRTCKN_PIDM, SHRTCKN_TERM_CODE, SHRTCKN_SEQ_NO, 1)
  AND SHRGRDE.ROWID = SOKODSF.F_GET_SHRGRDE_ROWID (SHRTCKG_VPDI_CODE,
    SHRTCKG_GRDE_CODE_FINAL, SHRTCKL_LEVL_CODE, SHRTCKN_TERM_CODE)
  AND SHRTCKN_TERM_CODE >= '200910'
  AND shrtckn_vpdi_code in ('ACC', 'CCA', 'CCD', 'CCCS', 'CNCC', 'FRCC',  'LCC', 'MCC', 'NJC', 'OJC','PCC', 'PPCC', 'RRCC', 'TSJC')
AND EXISTS (
SELECT 'X' 
  FROM
    SFRSTCR a
  WHERE
    sfrstcr_term_code >= '200910'
  AND SFRSTCR_GRDE_DATE IS NULL
  AND SHRTCKN_PIDM = A.SFRSTCR_PIDM 
  AND SHRTCKN_VPDI_CODE = A.SFRSTCR_VPDI_CODE
  AND SHRTCKN_CRN = A.SFRSTCR_CRN
  AND SHRTCKN_TERM_CODE = A.SFRSTCR_TERM_CODE)
  --vpdi filter

  
