/* Create re-create script for constrains before you drop them, but these down at the line that reads:
"PUT ME HERE"
/* 
/* SET SERVEROUTPUT ON;

DECLARE
   constraint_ddl   VARCHAR2 (4000);
BEGIN
   FOR X
      IN (SELECT DISTINCT CONSTRAINT_NAME
            FROM dba_cons_columns
           WHERE     owner = 'EDWMGR'
                 AND CONSTRAINT_NAME IN (SELECT CONSTRAINT_NAME
                                           FROM dba_constraints
                                          WHERE     owner = 'EDWMGR'
                                                AND R_CONSTRAINT_NAME =
                                                       'PK_WDT_PERSON'))
   LOOP
      constraint_ddl :=
         DBMS_LOB.SUBSTR (
            DBMS_METADATA.GET_DDL ('REF_CONSTRAINT',
                                   X.CONSTRAINT_NAME,
                                   'EDWMGR'),
            4000,
            1);
      constraint_ddl := constraint_ddl || ';';
      DBMS_OUTPUT.PUT_LINE (constraint_ddl);
   END LOOP;
END;
/

EXIT;
*/
/***************************************************************/
/***************************************************************/
/***************************************************************/
/***************************************************************/
/***************************************************************/
/***************************************************************/
/***************************************************************/
/***************************************************************/
/* MAKE SURE YOU DID WHAT I JUST SAID ABOVE BEFORE YOU MOVE ON */
/***************************************************************/
/***************************************************************/
/***************************************************************/
/***************************************************************/
/***************************************************************/
/***************************************************************/
/***************************************************************/

/* drop all foreign keys
   This script will create the statements to drop the proper constraints 
   --
SELECT 'alter table '||table_name||' drop constraint '||CONSTRAINT_NAME||';'
                                           FROM dba_constraints
                                          WHERE     owner = 'EDWMGR'
                                                AND R_CONSTRAINT_NAME =
                                                       'PK_WDT_PERSON';
*/                                                       
alter table WFZ_TEST drop constraint FZ4_TEST;
alter table WFZ_INTERACTION drop constraint FZ4_INTERACTION;
alter table WFZ_EM_CAMPAIGN drop constraint FZ5_EM_CAMPAIGN;
alter table WFZ_CONTACT drop constraint FZ4_CONTACT;
alter table WFZ_COMMUNICATION drop constraint FZ4_COMMUNICATION;
alter table WFZ_COMBINED_ADMISSIONS_SOURCE drop constraint FZ4_COMB_ADMISSIONS_SOURCE;
alter table WFZ_APPLICATION_DECISION drop constraint FZ4_APPLICATION_DECISION;
alter table WFZ_APPLICATION_COHORT drop constraint FZ4_APPLICATION_COHORT;
alter table WFT_SECONDARY_SCHOOL_SUBJECT drop constraint FK2_WFT_SECONDARY_SCHOOL_SUBJ;
alter table WFT_GRADE_CHANGE drop constraint FK4_GRADE_CHANGE;
alter table WFT_FINAID_AWARD_AID_YEAR drop constraint FK03_FINAID_AWRD_AIDY;
alter table WFT_CONTACT drop constraint FK2_CONTACT;
alter table WAZ_ADMISSIONS_FINAID_RECORD drop constraint FK06_WAZ_ADMS_FINAID;
alter table WAZ_STUDENT_ENGAGEMENT drop constraint FK04_WAZ_STUDENT_ENGAGEMENT;
alter table WAT_STUDENT_ENGAGEMENT drop constraint FK04_STUDENT_ENGAGEMENT;
alter table WFZ_COMBINED_COHORT drop constraint FZ4_COMBINED_COHORT;
alter table WFZ_COMBINED_ATTRIBUTE drop constraint FZ4_COMBINED_ATTRIBUTE;
alter table WFZ_COMBINED_ADMISSIONS_RECORD drop constraint FZ4_COMB_ADMISSIONS_RECORD;
alter table WFT_INTERACTION drop constraint FK2_INTERACTION;
alter table WFT_EM_CAMPAIGN drop constraint FK3_EM_CAMPAIGN;
alter table WFT_COMMUNICATION drop constraint FK2_COMMUNICATION;
alter table WFT_COMBINED_COHORT drop constraint FK3_COMBINED_COHORT;
alter table WFT_COMBINED_ATTRIBUTE drop constraint FK3_COMBINED_ATTRIBUTE;
alter table WFT_COMBINED_ADMISSIONS_RECORD drop constraint FK3_COMB_ADMISSIONS_RECORD;
alter table WAZ_STUDENT_PROGRESS drop constraint FK04_WAZ_STUDENT_PROG;
alter table WAT_STUDENT_PROGRESS drop constraint FK04_STUDENT_PROG;
alter table WFZ_STUDENT_COURSE drop constraint FK02_WFZ_STUDENT_COURSE;
alter table WFZ_FINAID_AWARD_AID_YEAR drop constraint FK05_FZ_FINAID_AWRD_AIDY;
alter table WFZ_FINAID_AWARD_ACAD_PERIOD drop constraint FK06_FZ_FINAID_AWRD_APRD;
alter table WFZ_FINAID_APPLICATION drop constraint FK06_FZ_FINAID_APPLICATION;
alter table WFZ_FEEDBACK drop constraint FZ04_FEEDBACK;
alter table WAT_ADMISSIONS_FINAID_RECORD drop constraint FK05_ADMISSIONS_FINAID;
alter table WFZ_APPLICATION_ATTRIBUTE drop constraint FZ4_APPLICATION_ATTRIBUTE;
alter table WFZ_ADMISSIONS_APPLICATION drop constraint FZ4_ADMISSIONS_APPLICATION;
alter table WFT_TEST drop constraint FK2_TEST;
alter table WFT_STUDENT_COURSE_ATTRIBUTE drop constraint FK08_STUDENT_COURSE_ATTRIBUTE;
alter table WFT_STUDENT_COURSE drop constraint FK02_STUDENT_COURSE;
alter table WFT_STUDENT_COHORT drop constraint FK5_STUDENT_COHORT;
alter table WFT_STUDENT_ATTRIBUTE drop constraint FK3_STUDENT_ATTRIBUTE;
alter table WFT_STUDENT_ACTIVITY drop constraint FK2_STUDENT_ACTIVITY;
alter table WFT_STUDENT drop constraint FK4_STUDENT;
alter table WFT_RETENTION_MULTI_YEAR drop constraint FK2_RET_MULTI_YEAR;
alter table WFT_RECRUITMENT_COHORT drop constraint FK3_RECRUITMENT_COHORT;
alter table WFT_RECRUITMENT_ATTRIBUTE drop constraint FK3_RECRUITMENT_ATTRIBUTE;
alter table WFT_RACE drop constraint FK2_RACE;
alter table WFT_PROSPECTIVE_STUDENT drop constraint FK2_PROSPECTIVE_STUDENT;
alter table WFT_POST_SECONDARY_SCHOOL drop constraint FK2_POST_SECONDARY_SCHOOL;
alter table WFT_INTEREST drop constraint FK2_INTEREST;
alter table WFT_HOLD drop constraint FK2_HOLD;
alter table WFT_FINAID_AWARD_ACAD_PERIOD drop constraint FK04_FINAID_AWRD_APRD;
alter table WFT_FINAID_APPLICATION drop constraint FK04_FINAID_APPLICATION;
alter table WFT_FEEDBACK drop constraint FK03_FEEDBACK;
alter table WFT_COMBINED_ADMISSIONS_SOURCE drop constraint FK3_COMB_ADMISSIONS_SOURCE;
alter table WFT_BANNER_COMMUNICATION drop constraint FK2_BANNER_COMMUNICATION;
alter table WFT_APPLICATION_REQUIREMENT drop constraint FK3_APPLICATION_REQUIREMENT;
alter table WFT_APPLICATION_RATING drop constraint FK3_APPLICATION_RATING;
alter table WFT_APPLICATION_DECISION drop constraint FK3_APPLICATION_DECISION;
alter table WFT_APPLICATION_COHORT drop constraint FK3_APPLICATION_COHORT;
alter table WFT_APPLICATION_ATTRIBUTE drop constraint FK3_APPLICATION_ATTRIBUTE;
alter table WFT_ADVISOR drop constraint FK5_ADVISOR;
alter table WFT_ADMISSIONS_RECRUITMENT drop constraint FK3_ADMISSIONS_RECRUITMENT;
alter table WFT_ATHLETIC drop constraint FK2_ATHLETIC;
alter table WFT_ADMISSIONS_APPLICATION drop constraint FK3_ADMISSIONS_APPLICATION;
alter table WFT_ADMINISTRATOR drop constraint FK3_ADMINISTRATOR;
alter table WFT_ACADEMIC_OUTCOME_HONOR drop constraint FK2_ACADEMIC_OUTCOME_HONOR;
alter table WFT_ACADEMIC_OUTCOME drop constraint FK4_ACADEMIC_OUTCOME;
commit;

/* Drop main index & constraint */
--commenting out next line for safety reasons
--alter table wdt_person drop constraint PK_WDT_PERSON drop index;

/***************************************************/
-- Now Delete the records from WDT_PERSON  --
/***************************************************/
--commenting out for safety purposes, but you need to run the next line
--delete from wdt_person where user_attribute_01 = 'CCCS';

/* Re-Create Index The New Way */
 CREATE UNIQUE INDEX PK_WDT_PERSON ON WDT_PERSON (PERSON_UID ASC);
 alter table WDT_PERSON add constraint PK_WDT_PERSON PRIMARY KEY ("PERSON_UID") USING INDEX PK_WDT_PERSON;
COMMIT;
 alter table wdt_person enable constraint pk_wdt_person;
 analyze index PK_WDT_PERSON compute statistics;
 
 
 /* Add the constraints back */
 ALTER TABLE "EDWMGR"."WFT_FINAID_AWARD_ACAD_PERIOD" ADD CONSTRAINT
"FK04_FINAID_AWRD_APRD" FOREIGN KEY ("PERSON_UID")
      REFERENCES
"EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE NOVALIDATE;

  ALTER TABLE "EDWMGR"."WFT_ADMINISTRATOR" ADD CONSTRAINT "FK3_ADMINISTRATOR"
FOREIGN KEY ("PERSON_UID")
      REFERENCES "EDWMGR"."WDT_PERSON"
("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFT_ATHLETIC" ADD CONSTRAINT "FK2_ATHLETIC" FOREIGN KEY
("PERSON_UID")
      REFERENCES "EDWMGR"."WDT_PERSON"
("PERSON_UID") ENABLE NOVALIDATE;

  ALTER TABLE "EDWMGR"."WFT_BANNER_COMMUNICATION" ADD CONSTRAINT
"FK2_BANNER_COMMUNICATION" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE
NOVALIDATE;

  ALTER TABLE "EDWMGR"."WFT_FINAID_AWARD_AID_YEAR" ADD CONSTRAINT
"FK03_FINAID_AWRD_AIDY" FOREIGN KEY ("PERSON_UID")
     REFERENCES
"EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE NOVALIDATE;

  ALTER TABLE "EDWMGR"."WFT_RECRUITMENT_ATTRIBUTE" ADD CONSTRAINT
"FK3_RECRUITMENT_ATTRIBUTE" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFT_INTERACTION" ADD CONSTRAINT "FK2_INTERACTION"
FOREIGN KEY ("PERSON_UID")
      REFERENCES "EDWMGR"."WDT_PERSON"
("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFZ_COMBINED_ADMISSIONS_RECORD" ADD CONSTRAINT
"FZ4_COMB_ADMISSIONS_RECORD" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFZ_EM_CAMPAIGN" ADD CONSTRAINT "FZ5_EM_CAMPAIGN"
FOREIGN KEY ("PERSON_UID")
      REFERENCES "EDWMGR"."WDT_PERSON"
("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFZ_INTERACTION" ADD CONSTRAINT "FZ4_INTERACTION"
FOREIGN KEY ("PERSON_UID")
      REFERENCES "EDWMGR"."WDT_PERSON"
("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFT_RACE" ADD CONSTRAINT "FK2_RACE" FOREIGN KEY
("PERSON_UID")
      REFERENCES "EDWMGR"."WDT_PERSON"
("PERSON_UID") ENABLE NOVALIDATE;

  ALTER TABLE "EDWMGR"."WFT_STUDENT_ATTRIBUTE" ADD CONSTRAINT
"FK3_STUDENT_ATTRIBUTE" FOREIGN KEY ("PERSON_UID")
      REFERENCES
"EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE NOVALIDATE;

  ALTER TABLE "EDWMGR"."WFT_STUDENT_COHORT" ADD CONSTRAINT "FK5_STUDENT_COHORT"
FOREIGN KEY ("PERSON_UID")
      REFERENCES "EDWMGR"."WDT_PERSON"
("PERSON_UID") ENABLE NOVALIDATE;

  ALTER TABLE "EDWMGR"."WFZ_ADMISSIONS_APPLICATION" ADD CONSTRAINT
"FZ4_ADMISSIONS_APPLICATION" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFZ_APPLICATION_ATTRIBUTE" ADD CONSTRAINT
"FZ4_APPLICATION_ATTRIBUTE" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFZ_APPLICATION_COHORT" ADD CONSTRAINT
"FZ4_APPLICATION_COHORT" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFZ_APPLICATION_DECISION" ADD CONSTRAINT
"FZ4_APPLICATION_DECISION" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFT_COMBINED_ATTRIBUTE" ADD CONSTRAINT
"FK3_COMBINED_ATTRIBUTE" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WAZ_STUDENT_ENGAGEMENT" ADD CONSTRAINT
"FK04_WAZ_STUDENT_ENGAGEMENT" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFT_STUDENT_COURSE" ADD CONSTRAINT
"FK02_STUDENT_COURSE" FOREIGN KEY ("PERSON_UID")
      REFERENCES
"EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE NOVALIDATE;

  ALTER TABLE "EDWMGR"."WFT_TEST" ADD CONSTRAINT "FK2_TEST" FOREIGN KEY
("PERSON_UID")
      REFERENCES "EDWMGR"."WDT_PERSON"
("PERSON_UID") ENABLE NOVALIDATE;

  ALTER TABLE "EDWMGR"."WFT_APPLICATION_ATTRIBUTE" ADD CONSTRAINT
"FK3_APPLICATION_ATTRIBUTE" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFT_FINAID_APPLICATION" ADD CONSTRAINT
"FK04_FINAID_APPLICATION" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE
NOVALIDATE;

  ALTER TABLE "EDWMGR"."WFT_RETENTION_MULTI_YEAR" ADD CONSTRAINT
"FK2_RET_MULTI_YEAR" FOREIGN KEY ("PERSON_UID")
      REFERENCES
"EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE NOVALIDATE;

  ALTER TABLE "EDWMGR"."WFT_SECONDARY_SCHOOL_SUBJECT" ADD CONSTRAINT
"FK2_WFT_SECONDARY_SCHOOL_SUBJ" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE
NOVALIDATE;

  ALTER TABLE "EDWMGR"."WFZ_COMBINED_ADMISSIONS_SOURCE" ADD CONSTRAINT
"FZ4_COMB_ADMISSIONS_SOURCE" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WAT_STUDENT_PROGRESS" ADD CONSTRAINT
"FK04_STUDENT_PROG" FOREIGN KEY ("PERSON_UID")
      REFERENCES
"EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE NOVALIDATE;

  ALTER TABLE "EDWMGR"."WAZ_STUDENT_PROGRESS" ADD CONSTRAINT
"FK04_WAZ_STUDENT_PROG" FOREIGN KEY ("PERSON_UID")
      REFERENCES
"EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFT_APPLICATION_DECISION" ADD CONSTRAINT
"FK3_APPLICATION_DECISION" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFT_POST_SECONDARY_SCHOOL" ADD CONSTRAINT
"FK2_POST_SECONDARY_SCHOOL" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE
NOVALIDATE;

  ALTER TABLE "EDWMGR"."WFZ_FEEDBACK" ADD CONSTRAINT "FZ04_FEEDBACK" FOREIGN
KEY ("PERSON_UID")
      REFERENCES "EDWMGR"."WDT_PERSON"
("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFZ_FINAID_AWARD_ACAD_PERIOD" ADD CONSTRAINT
"FK06_FZ_FINAID_AWRD_APRD" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WAZ_ADMISSIONS_FINAID_RECORD" ADD CONSTRAINT
"FK06_WAZ_ADMS_FINAID" FOREIGN KEY ("PERSON_UID")
      REFERENCES
"EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFT_COMBINED_ADMISSIONS_RECORD" ADD CONSTRAINT
"FK3_COMB_ADMISSIONS_RECORD" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WAT_STUDENT_ENGAGEMENT" ADD CONSTRAINT
"FK04_STUDENT_ENGAGEMENT" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE
NOVALIDATE;

  ALTER TABLE "EDWMGR"."WFT_COMBINED_ADMISSIONS_SOURCE" ADD CONSTRAINT
"FK3_COMB_ADMISSIONS_SOURCE" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFT_COMMUNICATION" ADD CONSTRAINT "FK2_COMMUNICATION"
FOREIGN KEY ("PERSON_UID")
      REFERENCES "EDWMGR"."WDT_PERSON"
("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFT_ACADEMIC_OUTCOME_HONOR" ADD CONSTRAINT
"FK2_ACADEMIC_OUTCOME_HONOR" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE
NOVALIDATE;

  ALTER TABLE "EDWMGR"."WFT_ADMISSIONS_RECRUITMENT" ADD CONSTRAINT
"FK3_ADMISSIONS_RECRUITMENT" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE
NOVALIDATE;

  ALTER TABLE "EDWMGR"."WFT_GRADE_CHANGE" ADD CONSTRAINT "FK4_GRADE_CHANGE"
FOREIGN KEY ("PERSON_UID")
      REFERENCES "EDWMGR"."WDT_PERSON"
("PERSON_UID") ENABLE NOVALIDATE;

  ALTER TABLE "EDWMGR"."WFZ_CONTACT" ADD CONSTRAINT "FZ4_CONTACT" FOREIGN KEY
("PERSON_UID")
      REFERENCES "EDWMGR"."WDT_PERSON"
("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFZ_COMBINED_ATTRIBUTE" ADD CONSTRAINT
"FZ4_COMBINED_ATTRIBUTE" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFZ_COMBINED_COHORT" ADD CONSTRAINT
"FZ4_COMBINED_COHORT" FOREIGN KEY ("PERSON_UID")
      REFERENCES
"EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFZ_COMMUNICATION" ADD CONSTRAINT "FZ4_COMMUNICATION"
FOREIGN KEY ("PERSON_UID")
      REFERENCES "EDWMGR"."WDT_PERSON"
("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFZ_FINAID_AWARD_AID_YEAR" ADD CONSTRAINT
"FK05_FZ_FINAID_AWRD_AIDY" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFZ_STUDENT_COURSE" ADD CONSTRAINT
"FK02_WFZ_STUDENT_COURSE" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFZ_TEST" ADD CONSTRAINT "FZ4_TEST" FOREIGN KEY
("PERSON_UID")
      REFERENCES "EDWMGR"."WDT_PERSON"
("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFT_APPLICATION_REQUIREMENT" ADD CONSTRAINT
"FK3_APPLICATION_REQUIREMENT" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFT_CONTACT" ADD CONSTRAINT "FK2_CONTACT" FOREIGN KEY
("PERSON_UID")
      REFERENCES "EDWMGR"."WDT_PERSON"
("PERSON_UID") ENABLE NOVALIDATE;

  ALTER TABLE "EDWMGR"."WFT_PROSPECTIVE_STUDENT" ADD CONSTRAINT
"FK2_PROSPECTIVE_STUDENT" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE
NOVALIDATE;

  ALTER TABLE "EDWMGR"."WFT_RECRUITMENT_COHORT" ADD CONSTRAINT
"FK3_RECRUITMENT_COHORT" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFT_EM_CAMPAIGN" ADD CONSTRAINT "FK3_EM_CAMPAIGN"
FOREIGN KEY ("PERSON_UID")
      REFERENCES "EDWMGR"."WDT_PERSON"
("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFT_INTEREST" ADD CONSTRAINT "FK2_INTEREST" FOREIGN KEY
("PERSON_UID")
      REFERENCES "EDWMGR"."WDT_PERSON"
("PERSON_UID") ENABLE NOVALIDATE;

  ALTER TABLE "EDWMGR"."WFT_ADMISSIONS_APPLICATION" ADD CONSTRAINT
"FK3_ADMISSIONS_APPLICATION" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE
NOVALIDATE;

  ALTER TABLE "EDWMGR"."WFT_ADVISOR" ADD CONSTRAINT "FK5_ADVISOR" FOREIGN KEY
("PERSON_UID")
      REFERENCES "EDWMGR"."WDT_PERSON"
("PERSON_UID") ENABLE NOVALIDATE;

  ALTER TABLE "EDWMGR"."WFT_STUDENT_COURSE_ATTRIBUTE" ADD CONSTRAINT
"FK08_STUDENT_COURSE_ATTRIBUTE" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE
NOVALIDATE;

  ALTER TABLE "EDWMGR"."WFT_ACADEMIC_OUTCOME" ADD CONSTRAINT
"FK4_ACADEMIC_OUTCOME" FOREIGN KEY ("PERSON_UID")
      REFERENCES
"EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE NOVALIDATE;

  ALTER TABLE "EDWMGR"."WFT_APPLICATION_COHORT" ADD CONSTRAINT
"FK3_APPLICATION_COHORT" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFT_APPLICATION_RATING" ADD CONSTRAINT
"FK3_APPLICATION_RATING" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFT_FEEDBACK" ADD CONSTRAINT "FK03_FEEDBACK" FOREIGN
KEY ("PERSON_UID")
      REFERENCES "EDWMGR"."WDT_PERSON"
("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WFT_HOLD" ADD CONSTRAINT "FK2_HOLD" FOREIGN KEY
("PERSON_UID")
      REFERENCES "EDWMGR"."WDT_PERSON"
("PERSON_UID") ENABLE NOVALIDATE;

  ALTER TABLE "EDWMGR"."WFT_STUDENT" ADD CONSTRAINT "FK4_STUDENT" FOREIGN KEY
("PERSON_UID")
      REFERENCES "EDWMGR"."WDT_PERSON"
("PERSON_UID") ENABLE NOVALIDATE;

  ALTER TABLE "EDWMGR"."WFT_STUDENT_ACTIVITY" ADD CONSTRAINT
"FK2_STUDENT_ACTIVITY" FOREIGN KEY ("PERSON_UID")
      REFERENCES
"EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE NOVALIDATE;

  ALTER TABLE "EDWMGR"."WFZ_FINAID_APPLICATION" ADD CONSTRAINT
"FK06_FZ_FINAID_APPLICATION" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE;

  ALTER TABLE "EDWMGR"."WAT_ADMISSIONS_FINAID_RECORD" ADD CONSTRAINT
"FK05_ADMISSIONS_FINAID" FOREIGN KEY ("PERSON_UID")

REFERENCES "EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE
NOVALIDATE;

  ALTER TABLE "EDWMGR"."WFT_COMBINED_COHORT" ADD CONSTRAINT
"FK3_COMBINED_COHORT" FOREIGN KEY ("PERSON_UID")
      REFERENCES
"EDWMGR"."WDT_PERSON" ("PERSON_UID") ENABLE;
COMMIT;