ALTER TABLE EDWMGR.WFT_ATHLETIC
  DROP CONSTRAINT FK2_ATHLETIC;

ALTER TABLE EDWMGR.WAT_ADMISSIONS_FINAID_RECORD
  DROP CONSTRAINT FK05_ADMISSIONS_FINAID;


ALTER TABLE EDWMGR.WAT_STUDENT_ENGAGEMENT
  DROP CONSTRAINT FK04_STUDENT_ENGAGEMENT;


ALTER TABLE EDWMGR.WAT_STUDENT_PROGRESS
  DROP CONSTRAINT FK04_STUDENT_PROG;


ALTER TABLE EDWMGR.WAZ_ADMISSIONS_FINAID_RECORD
  DROP CONSTRAINT FK06_WAZ_ADMS_FINAID;


ALTER TABLE EDWMGR.WAZ_STUDENT_ENGAGEMENT
  DROP CONSTRAINT FK04_WAZ_STUDENT_ENGAGEMENT;


ALTER TABLE EDWMGR.WAZ_STUDENT_PROGRESS
  DROP CONSTRAINT FK04_WAZ_STUDENT_PROG;


ALTER TABLE EDWMGR.WFT_ACADEMIC_OUTCOME
  DROP CONSTRAINT FK4_ACADEMIC_OUTCOME;


ALTER TABLE EDWMGR.WFT_ACADEMIC_OUTCOME_HONOR
  DROP CONSTRAINT FK2_ACADEMIC_OUTCOME_HONOR;


ALTER TABLE EDWMGR.WFT_ADMINISTRATOR
  DROP CONSTRAINT FK3_ADMINISTRATOR;


ALTER TABLE EDWMGR.WFT_ADMINISTRATOR
  DROP CONSTRAINT FK5_ADMINISTRATOR;


ALTER TABLE EDWMGR.WFT_ADMISSIONS_APPLICATION
  DROP CONSTRAINT FK3_ADMISSIONS_APPLICATION;


ALTER TABLE EDWMGR.WFT_ADMISSIONS_RECRUITMENT
  DROP CONSTRAINT FK3_ADMISSIONS_RECRUITMENT;


ALTER TABLE EDWMGR.WFT_ADVISOR
  DROP CONSTRAINT FK5_ADVISOR;


ALTER TABLE EDWMGR.WFT_ADVISOR
  DROP CONSTRAINT FK7_ADVISOR;


ALTER TABLE EDWMGR.WFT_APPLICATION_ATTRIBUTE
  DROP CONSTRAINT FK3_APPLICATION_ATTRIBUTE;


ALTER TABLE EDWMGR.WFT_APPLICATION_COHORT
  DROP CONSTRAINT FK3_APPLICATION_COHORT;


ALTER TABLE EDWMGR.WFT_APPLICATION_DECISION
  DROP CONSTRAINT FK3_APPLICATION_DECISION;


ALTER TABLE EDWMGR.WFT_APPLICATION_RATING
  DROP CONSTRAINT FK3_APPLICATION_RATING;


ALTER TABLE EDWMGR.WFT_APPLICATION_RATING
  DROP CONSTRAINT FK6_APPLICATION_RATING;


ALTER TABLE EDWMGR.WFT_APPLICATION_REQUIREMENT
  DROP CONSTRAINT FK3_APPLICATION_REQUIREMENT;


ALTER TABLE EDWMGR.WFT_BANNER_COMMUNICATION
  DROP CONSTRAINT FK2_BANNER_COMMUNICATION;


ALTER TABLE EDWMGR.WFT_COMBINED_ADMISSIONS_RECORD
  DROP CONSTRAINT FK3_COMB_ADMISSIONS_RECORD;


ALTER TABLE EDWMGR.WFT_COMBINED_ADMISSIONS_SOURCE
  DROP CONSTRAINT FK3_COMB_ADMISSIONS_SOURCE;


ALTER TABLE EDWMGR.WFT_COMBINED_ATTRIBUTE
  DROP CONSTRAINT FK3_COMBINED_ATTRIBUTE;


ALTER TABLE EDWMGR.WFT_COMBINED_COHORT
  DROP CONSTRAINT FK3_COMBINED_COHORT;


ALTER TABLE EDWMGR.WFT_COMMUNICATION
  DROP CONSTRAINT FK2_COMMUNICATION;


ALTER TABLE EDWMGR.WFT_CONTACT
  DROP CONSTRAINT FK2_CONTACT;


ALTER TABLE EDWMGR.WFT_EM_CAMPAIGN
  DROP CONSTRAINT FK3_EM_CAMPAIGN;


ALTER TABLE EDWMGR.WFT_FEEDBACK
  DROP CONSTRAINT FK03_FEEDBACK;


ALTER TABLE EDWMGR.WFT_FINAID_APPLICATION
  DROP CONSTRAINT FK04_FINAID_APPLICATION;


ALTER TABLE EDWMGR.WFT_FINAID_AWARD_ACAD_PERIOD
  DROP CONSTRAINT FK04_FINAID_AWRD_APRD;


ALTER TABLE EDWMGR.WFT_FINAID_AWARD_AID_YEAR
  DROP CONSTRAINT FK03_FINAID_AWRD_AIDY;


ALTER TABLE EDWMGR.WFT_GRADE_CHANGE
  DROP CONSTRAINT FK4_GRADE_CHANGE;


ALTER TABLE EDWMGR.WFT_HOLD
  DROP CONSTRAINT FK2_HOLD;


ALTER TABLE EDWMGR.WFT_INTERACTION
  DROP CONSTRAINT FK2_INTERACTION;


ALTER TABLE EDWMGR.WFT_INTEREST
  DROP CONSTRAINT FK2_INTEREST;


ALTER TABLE EDWMGR.WFT_POST_SECONDARY_SCHOOL
  DROP CONSTRAINT FK2_POST_SECONDARY_SCHOOL;


ALTER TABLE EDWMGR.WFT_PROSPECTIVE_STUDENT
  DROP CONSTRAINT FK2_PROSPECTIVE_STUDENT;


ALTER TABLE EDWMGR.WFT_RACE
  DROP CONSTRAINT FK2_RACE;


ALTER TABLE EDWMGR.WFT_RECRUITMENT_ATTRIBUTE
  DROP CONSTRAINT FK3_RECRUITMENT_ATTRIBUTE;


ALTER TABLE EDWMGR.WFT_RECRUITMENT_COHORT
  DROP CONSTRAINT FK3_RECRUITMENT_COHORT;


ALTER TABLE EDWMGR.WFT_RETENTION_MULTI_YEAR
  DROP CONSTRAINT FK2_RET_MULTI_YEAR;


ALTER TABLE EDWMGR.WFT_SECONDARY_SCHOOL_SUBJECT
  DROP CONSTRAINT FK2_WFT_SECONDARY_SCHOOL_SUBJ;


ALTER TABLE EDWMGR.WFT_STUDENT
  DROP CONSTRAINT FK4_STUDENT;


ALTER TABLE EDWMGR.WFT_STUDENT_ACTIVITY
  DROP CONSTRAINT FK2_STUDENT_ACTIVITY;


ALTER TABLE EDWMGR.WFT_STUDENT_ATTRIBUTE
  DROP CONSTRAINT FK3_STUDENT_ATTRIBUTE;


ALTER TABLE EDWMGR.WFT_STUDENT_COHORT
  DROP CONSTRAINT FK5_STUDENT_COHORT;


ALTER TABLE EDWMGR.WFT_STUDENT_COURSE
  DROP CONSTRAINT FK02_STUDENT_COURSE;


ALTER TABLE EDWMGR.WFT_STUDENT_COURSE_ATTRIBUTE
  DROP CONSTRAINT FK08_STUDENT_COURSE_ATTRIBUTE;


ALTER TABLE EDWMGR.WFT_TEST
  DROP CONSTRAINT FK2_TEST;


ALTER TABLE EDWMGR.WFZ_ADMISSIONS_APPLICATION
  DROP CONSTRAINT FZ4_ADMISSIONS_APPLICATION;


ALTER TABLE EDWMGR.WFZ_APPLICATION_ATTRIBUTE
  DROP CONSTRAINT FZ4_APPLICATION_ATTRIBUTE;


ALTER TABLE EDWMGR.WFZ_APPLICATION_COHORT
  DROP CONSTRAINT FZ4_APPLICATION_COHORT;


ALTER TABLE EDWMGR.WFZ_APPLICATION_DECISION
  DROP CONSTRAINT FZ4_APPLICATION_DECISION;


ALTER TABLE EDWMGR.WFZ_COMBINED_ADMISSIONS_RECORD
  DROP CONSTRAINT FZ4_COMB_ADMISSIONS_RECORD;


ALTER TABLE EDWMGR.WFZ_COMBINED_ADMISSIONS_SOURCE
  DROP CONSTRAINT FZ4_COMB_ADMISSIONS_SOURCE;


ALTER TABLE EDWMGR.WFZ_COMBINED_ATTRIBUTE
  DROP CONSTRAINT FZ4_COMBINED_ATTRIBUTE;


ALTER TABLE EDWMGR.WFZ_COMBINED_COHORT
  DROP CONSTRAINT FZ4_COMBINED_COHORT;


ALTER TABLE EDWMGR.WFZ_COMMUNICATION
  DROP CONSTRAINT FZ4_COMMUNICATION;


ALTER TABLE EDWMGR.WFZ_CONTACT
  DROP CONSTRAINT FZ4_CONTACT;


ALTER TABLE EDWMGR.WFZ_EM_CAMPAIGN
  DROP CONSTRAINT FZ5_EM_CAMPAIGN;


ALTER TABLE EDWMGR.WFZ_FEEDBACK
  DROP CONSTRAINT FZ04_FEEDBACK;


ALTER TABLE EDWMGR.WFZ_FINAID_APPLICATION
  DROP CONSTRAINT FK06_FZ_FINAID_APPLICATION;


ALTER TABLE EDWMGR.WFZ_FINAID_AWARD_ACAD_PERIOD
  DROP CONSTRAINT FK06_FZ_FINAID_AWRD_APRD;


ALTER TABLE EDWMGR.WFZ_FINAID_AWARD_AID_YEAR
  DROP CONSTRAINT FK05_FZ_FINAID_AWRD_AIDY;


ALTER TABLE EDWMGR.WFZ_INTERACTION
  DROP CONSTRAINT FZ4_INTERACTION;


ALTER TABLE EDWMGR.WFZ_STUDENT_COURSE
  DROP CONSTRAINT FK02_WFZ_STUDENT_COURSE;


ALTER TABLE EDWMGR.WFZ_TEST
  DROP CONSTRAINT FZ4_TEST;