ALTER TABLE EDWMGR.WFT_ATHLETIC ADD (
  CONSTRAINT FK2_ATHLETIC 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);
  
  
ALTER TABLE EDWMGR.WAT_ADMISSIONS_FINAID_RECORD ADD (
  CONSTRAINT FK05_ADMISSIONS_FINAID 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WAT_STUDENT_ENGAGEMENT ADD (
  CONSTRAINT FK04_STUDENT_ENGAGEMENT 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WAT_STUDENT_PROGRESS ADD (
  CONSTRAINT FK04_STUDENT_PROG 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WAZ_ADMISSIONS_FINAID_RECORD ADD (
  CONSTRAINT FK06_WAZ_ADMS_FINAID 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WAZ_STUDENT_ENGAGEMENT ADD (
  CONSTRAINT FK04_WAZ_STUDENT_ENGAGEMENT 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WAZ_STUDENT_PROGRESS ADD (
  CONSTRAINT FK04_WAZ_STUDENT_PROG 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_ACADEMIC_OUTCOME ADD (
  CONSTRAINT FK4_ACADEMIC_OUTCOME 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_ACADEMIC_OUTCOME_HONOR ADD (
  CONSTRAINT FK2_ACADEMIC_OUTCOME_HONOR 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_ADMINISTRATOR ADD (
  CONSTRAINT FK3_ADMINISTRATOR 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_ADMINISTRATOR ADD (
  CONSTRAINT FK5_ADMINISTRATOR 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_ADMISSIONS_APPLICATION ADD (
  CONSTRAINT FK3_ADMISSIONS_APPLICATION 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_ADMISSIONS_RECRUITMENT ADD (
  CONSTRAINT FK3_ADMISSIONS_RECRUITMENT 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_ADVISOR ADD (
  CONSTRAINT FK5_ADVISOR 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_ADVISOR ADD (
  CONSTRAINT FK7_ADVISOR 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_APPLICATION_ATTRIBUTE ADD (
  CONSTRAINT FK3_APPLICATION_ATTRIBUTE 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_APPLICATION_COHORT ADD (
  CONSTRAINT FK3_APPLICATION_COHORT 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_APPLICATION_DECISION ADD (
  CONSTRAINT FK3_APPLICATION_DECISION 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_APPLICATION_RATING ADD (
  CONSTRAINT FK3_APPLICATION_RATING 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_APPLICATION_RATING ADD (
  CONSTRAINT FK6_APPLICATION_RATING 
  FOREIGN KEY (person_uid, mif_value_vc) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_APPLICATION_REQUIREMENT ADD (
  CONSTRAINT FK3_APPLICATION_REQUIREMENT 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_BANNER_COMMUNICATION ADD (
  CONSTRAINT FK2_BANNER_COMMUNICATION 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_COMBINED_ADMISSIONS_RECORD ADD (
  CONSTRAINT FK3_COMB_ADMISSIONS_RECORD 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_COMBINED_ADMISSIONS_SOURCE ADD (
  CONSTRAINT FK3_COMB_ADMISSIONS_SOURCE 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_COMBINED_ATTRIBUTE ADD (
  CONSTRAINT FK3_COMBINED_ATTRIBUTE 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_COMBINED_COHORT ADD (
  CONSTRAINT FK3_COMBINED_COHORT 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_COMMUNICATION ADD (
  CONSTRAINT FK2_COMMUNICATION 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_CONTACT ADD (
  CONSTRAINT FK2_CONTACT 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_EM_CAMPAIGN ADD (
  CONSTRAINT FK3_EM_CAMPAIGN 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_FEEDBACK ADD (
  CONSTRAINT FK03_FEEDBACK 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_FINAID_APPLICATION ADD (
  CONSTRAINT FK04_FINAID_APPLICATION 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_FINAID_AWARD_ACAD_PERIOD ADD (
  CONSTRAINT FK04_FINAID_AWRD_APRD 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_FINAID_AWARD_AID_YEAR ADD (
  CONSTRAINT FK03_FINAID_AWRD_AIDY 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_GRADE_CHANGE ADD (
  CONSTRAINT FK4_GRADE_CHANGE 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_HOLD ADD (
  CONSTRAINT FK2_HOLD 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_INTERACTION ADD (
  CONSTRAINT FK2_INTERACTION 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_INTEREST ADD (
  CONSTRAINT FK2_INTEREST 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_POST_SECONDARY_SCHOOL ADD (
  CONSTRAINT FK2_POST_SECONDARY_SCHOOL 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_PROSPECTIVE_STUDENT ADD (
  CONSTRAINT FK2_PROSPECTIVE_STUDENT 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_RACE ADD (
  CONSTRAINT FK2_RACE 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_RECRUITMENT_ATTRIBUTE ADD (
  CONSTRAINT FK3_RECRUITMENT_ATTRIBUTE 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_RECRUITMENT_COHORT ADD (
  CONSTRAINT FK3_RECRUITMENT_COHORT 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_RETENTION_MULTI_YEAR ADD (
  CONSTRAINT FK2_RET_MULTI_YEAR 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_SECONDARY_SCHOOL_SUBJECT ADD (
  CONSTRAINT FK2_WFT_SECONDARY_SCHOOL_SUBJ 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_STUDENT ADD (
  CONSTRAINT FK4_STUDENT 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_STUDENT_ACTIVITY ADD (
  CONSTRAINT FK2_STUDENT_ACTIVITY 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_STUDENT_ATTRIBUTE ADD (
  CONSTRAINT FK3_STUDENT_ATTRIBUTE 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_STUDENT_COHORT ADD (
  CONSTRAINT FK5_STUDENT_COHORT 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_STUDENT_COURSE ADD (
  CONSTRAINT FK02_STUDENT_COURSE 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_STUDENT_COURSE_ATTRIBUTE ADD (
  CONSTRAINT FK08_STUDENT_COURSE_ATTRIBUTE 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFT_TEST ADD (
  CONSTRAINT FK2_TEST 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFZ_ADMISSIONS_APPLICATION ADD (
  CONSTRAINT FZ4_ADMISSIONS_APPLICATION 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFZ_APPLICATION_ATTRIBUTE ADD (
  CONSTRAINT FZ4_APPLICATION_ATTRIBUTE 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFZ_APPLICATION_COHORT ADD (
  CONSTRAINT FZ4_APPLICATION_COHORT 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFZ_APPLICATION_DECISION ADD (
  CONSTRAINT FZ4_APPLICATION_DECISION 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFZ_COMBINED_ADMISSIONS_RECORD ADD (
  CONSTRAINT FZ4_COMB_ADMISSIONS_RECORD 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFZ_COMBINED_ADMISSIONS_SOURCE ADD (
  CONSTRAINT FZ4_COMB_ADMISSIONS_SOURCE 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFZ_COMBINED_ATTRIBUTE ADD (
  CONSTRAINT FZ4_COMBINED_ATTRIBUTE 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFZ_COMBINED_COHORT ADD (
  CONSTRAINT FZ4_COMBINED_COHORT 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFZ_COMMUNICATION ADD (
  CONSTRAINT FZ4_COMMUNICATION 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFZ_CONTACT ADD (
  CONSTRAINT FZ4_CONTACT 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFZ_EM_CAMPAIGN ADD (
  CONSTRAINT FZ5_EM_CAMPAIGN 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFZ_FEEDBACK ADD (
  CONSTRAINT FZ04_FEEDBACK 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFZ_FINAID_APPLICATION ADD (
  CONSTRAINT FK06_FZ_FINAID_APPLICATION 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFZ_FINAID_AWARD_ACAD_PERIOD ADD (
  CONSTRAINT FK06_FZ_FINAID_AWRD_APRD 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFZ_FINAID_AWARD_AID_YEAR ADD (
  CONSTRAINT FK05_FZ_FINAID_AWRD_AIDY 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFZ_INTERACTION ADD (
  CONSTRAINT FZ4_INTERACTION 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFZ_STUDENT_COURSE ADD (
  CONSTRAINT FK02_WFZ_STUDENT_COURSE 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);


ALTER TABLE EDWMGR.WFZ_TEST ADD (
  CONSTRAINT FZ4_TEST 
  FOREIGN KEY (PERSON_UID, MIF_VALUE_VC) 
  REFERENCES EDWMGR.WDT_PERSON (PERSON_UID, USER_ATTRIBUTE_01)
  ENABLE VALIDATE);
