SELECT DISTINCT * FROM
(SELECT  'ALTER TABLE '|| table2 ||
       ' ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));'
FROM
  (SELECT a.table_name table1, b.table_name table2, b.constraint_name table2_fkey
  FROM user_constraints a, user_constraints b 
  WHERE a.constraint_type IN('P', 'U') 
  AND b.constraint_type = 'R' 
  AND a.constraint_name = b.r_constraint_name 
  AND a.table_name != b.table_name
  AND b.table_name <> 'WDT_PERSON')
CONNECT BY PRIOR  table2 = table1 AND LEVEL <= 5
START WITH table1 = 'WDT_PERSON');

/* Creates this: 
ALTER TABLE WAT_ADMISSIONS_FINAID_RECORD ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_COMBINED_ADMISSIONS_SOURCE ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_CONTACT ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_SECONDARY_SCHOOL_SUBJECT ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_STUDENT_COURSE_ATTRIBUTE ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFZ_COMBINED_ADMISSIONS_RECORD ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFZ_FINAID_APPLICATION ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WAZ_ADMISSIONS_FINAID_RECORD ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WAZ_STUDENT_PROGRESS ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_ADMINISTRATOR ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_APPLICATION_COHORT ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_FINAID_AWARD_ACAD_PERIOD ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_FINAID_AWARD_AID_YEAR ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_INTEREST ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE wft_course_instructor ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE wft_meeting_time ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE wft_course_section ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE wft_institution ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_STUDENT_COURSE ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFZ_COMBINED_ADMISSIONS_SOURCE ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_APPLICATION_REQUIREMENT ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_COMBINED_ADMISSIONS_RECORD ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_STUDENT ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_STUDENT_COHORT ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFZ_STUDENT_COURSE ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WAT_STUDENT_PROGRESS ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_APPLICATION_RATING ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_FEEDBACK ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_GRADE_CHANGE ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_PROSPECTIVE_STUDENT ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFZ_APPLICATION_ATTRIBUTE ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFZ_COMBINED_ATTRIBUTE ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFZ_COMMUNICATION ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_ACADEMIC_OUTCOME ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_ADMISSIONS_RECRUITMENT ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_APPLICATION_ATTRIBUTE ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_BANNER_COMMUNICATION ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_COMBINED_ATTRIBUTE ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_EM_CAMPAIGN ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_POST_SECONDARY_SCHOOL ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFZ_APPLICATION_DECISION ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFZ_CONTACT ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFZ_FINAID_AWARD_AID_YEAR ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFZ_TEST ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WAT_STUDENT_ENGAGEMENT ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WAZ_STUDENT_ENGAGEMENT ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_ACADEMIC_OUTCOME_HONOR ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_ADMISSIONS_APPLICATION ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_ADVISOR ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_APPLICATION_DECISION ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_COMMUNICATION ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_FINAID_APPLICATION ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_HOLD ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_RETENTION_MULTI_YEAR ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_STUDENT_ATTRIBUTE ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFZ_COMBINED_COHORT ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFZ_EM_CAMPAIGN ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFZ_INTERACTION ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_ATHLETIC ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_COMBINED_COHORT ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_INTERACTION ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_RECRUITMENT_ATTRIBUTE ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFZ_ADMISSIONS_APPLICATION ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFZ_APPLICATION_COHORT ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_RACE ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_RECRUITMENT_COHORT ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_STUDENT_ACTIVITY ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFT_TEST ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFZ_FEEDBACK ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
ALTER TABLE WFZ_FINAID_AWARD_ACAD_PERIOD ADD MIF_VALUE_VC GENERATED ALWAYS AS (F_GET_MIF_VALUE_4_VC(MULTI_SOURCE_KEY));
*/