SELECT
/* JOINER.OUTGRP1 */
  "WDT_MULTI_SOURCE"."MULTI_SOURCE_KEY" "MULTI_SOURCE_KEY",
  "WTT_POST_SECONDARY_CLEAN"."PERSON_UID" "PERSON_UID",
  "WDT_DEMOGRAPHIC"."DEMOGRAPHIC_KEY" "DEMOGRAPHIC_KEY",
  "WDT_POST_SECONDARY_SCHOOL"."POST_SECONDARY_SCHOOL_KEY" "POST_SECONDARY_SCHOOL_KEY",
  ( "WTT_POST_SECONDARY_CLEAN"."PERSON_UID"  * 100  )  +  "WDT_MULTI_SOURCE"."MULTI_SOURCE_KEY"/* ATTRIBUTE EXPRESSION.OUTGRP1.POST_SECONDARY_SCHOOL_GRP_KEY: EXPRESSION */ "POST_SECONDARY_SCHOOL_GRP_KEY",
  "WDT_INSTITUTION"."INSTITUTION_KEY" "INSTITUTION_KEY",
  "WTT_POST_SECONDARY_CLEAN"."POST_SECONDARY_SEQUENCE_NUMBER" "POST_SECONDARY_SEQUENCE_NUMBER",
  "WTT_POST_SECONDARY_CLEAN"."POST_SECONDARY_ATTEND_FROM" "POST_SECONDARY_ATTEND_FROM",
  "WTT_POST_SECONDARY_CLEAN"."POST_SECONDARY_ATTEND_TO" "POST_SECONDARY_ATTEND_TO",
  "WTT_POST_SECONDARY_CLEAN"."POST_SECONDARY_DEGREE_DATE" "POST_SECONDARY_DEGREE_DATE",
  "WTT_POST_SECONDARY_CLEAN"."LAST_POST_SECONDARY_IND" "LAST_POST_SECONDARY_IND",
  "WTT_POST_SECONDARY_CLEAN"."HIGHEST_DEGREE_AWARDED_IND" "HIGHEST_DEGREE_AWARDED_IND",
  "WTT_POST_SECONDARY_CLEAN"."OUTCOME_AWARD_IND" "OUTCOME_AWARD_IND",
  "WTT_POST_SECONDARY_CLEAN"."POST_SECONDARY_GPA" "POST_SECONDARY_GPA",
  "WTT_POST_SECONDARY_CLEAN"."POST_SECONDARY_TRANS_CREDITS" "POST_SECONDARY_TRANS_CREDITS",
  "WTT_POST_SECONDARY_CLEAN"."USER_MEASURE_01" "USER_MEASURE_01",
  "WTT_POST_SECONDARY_CLEAN"."USER_MEASURE_02" "USER_MEASURE_02",
  "WTT_POST_SECONDARY_CLEAN"."USER_MEASURE_03" "USER_MEASURE_03",
  "WTT_POST_SECONDARY_CLEAN"."USER_MEASURE_04" "USER_MEASURE_04",
  "WTT_POST_SECONDARY_CLEAN"."USER_MEASURE_05" "USER_MEASURE_05",
  "WDT_MULTI_SOURCE"."SYSTEM_LOAD_PROCESS" "SYSTEM_LOAD_PROCESS",
  "WTT_POST_SECONDARY_CLEAN"."SYSTEM_LOAD_TMSTMP" "SYSTEM_LOAD_TMSTMP_4"
FROM
  "EDWMGR"."WDT_MULTI_SOURCE"  "WDT_MULTI_SOURCE",
"EDWMGR"."WDT_DEMOGRAPHIC"  "WDT_DEMOGRAPHIC",
"EDWMGR"."WDT_INSTITUTION"  "WDT_INSTITUTION",
"EDWMGR"."WDT_POST_SECONDARY_SCHOOL"  "WDT_POST_SECONDARY_SCHOOL",
"WTT_POST_SECONDARY_CLEAN"  "WTT_POST_SECONDARY_CLEAN"
  WHERE 
  ( "WDT_MULTI_SOURCE"."MULTI_SOURCE" = "WTT_POST_SECONDARY_CLEAN"."MULTI_SOURCE_WV" )  AND
  ( "WDT_MULTI_SOURCE"."PROCESS_GROUP" = "WTT_POST_SECONDARY_CLEAN"."PROCESS_GROUP_WV" )  AND
  ( "WDT_MULTI_SOURCE"."ADMINISTRATIVE_GROUP" = "WTT_POST_SECONDARY_CLEAN"."ADMINISTRATIVE_GROUP_WV" )  AND
  ( "WDT_MULTI_SOURCE"."USER_ATTRIBUTE_01" = "WTT_POST_SECONDARY_CLEAN"."MSRC_USER_ATTRIBUTE_01_WV" )  AND
  ( "WDT_MULTI_SOURCE"."USER_ATTRIBUTE_02" = "WTT_POST_SECONDARY_CLEAN"."MSRC_USER_ATTRIBUTE_02_WV" )  AND
  ( "WDT_MULTI_SOURCE"."USER_ATTRIBUTE_03" = "WTT_POST_SECONDARY_CLEAN"."MSRC_USER_ATTRIBUTE_03_WV" )  AND
  ( "WDT_MULTI_SOURCE"."USER_ATTRIBUTE_04" = "WTT_POST_SECONDARY_CLEAN"."MSRC_USER_ATTRIBUTE_04_WV" )  AND
  ( "WDT_MULTI_SOURCE"."USER_ATTRIBUTE_05" = "WTT_POST_SECONDARY_CLEAN"."MSRC_USER_ATTRIBUTE_05_WV" )  AND
  ( "WDT_INSTITUTION"."INSTITUTION" = "WTT_POST_SECONDARY_CLEAN"."INSTITUTION_WV" )  AND
  ( "WDT_INSTITUTION"."USER_ATTRIBUTE_01" = "WTT_POST_SECONDARY_CLEAN"."MULTI_SOURCE_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."GENDER" = "WTT_POST_SECONDARY_CLEAN"."GENDER_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."ETHNICITY_CATEGORY" = "WTT_POST_SECONDARY_CLEAN"."ETHNICITY_CATEGORY_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."HISPANIC_LATINO_ETHNICITY_IND" = "WTT_POST_SECONDARY_CLEAN"."HISPANIC_LATINO_ETHN_IND_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."ASIAN_IND" = "WTT_POST_SECONDARY_CLEAN"."ASIAN_IND_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."NATIVE_AMERICAN_OR_ALASKAN_IND" = "WTT_POST_SECONDARY_CLEAN"."NATIVE_AMER_OR_ALASKAN_IND_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."BLACK_OR_AFRICAN_IND" = "WTT_POST_SECONDARY_CLEAN"."BLACK_OR_AFRICAN_IND_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."PACIFIC_ISLANDER_IND" = "WTT_POST_SECONDARY_CLEAN"."PACIFIC_ISLANDER_IND_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."WHITE_IND" = "WTT_POST_SECONDARY_CLEAN"."WHITE_IND_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."ETHNICITY" = "WTT_POST_SECONDARY_CLEAN"."ETHNICITY_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."DECEASED_IND" = "WTT_POST_SECONDARY_CLEAN"."DECEASED_IND_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."CITIZENSHIP_IND" = "WTT_POST_SECONDARY_CLEAN"."CITIZENSHIP_IND_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."CITIZENSHIP_TYPE" = "WTT_POST_SECONDARY_CLEAN"."CITIZENSHIP_TYPE_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."VISA_TYPE" = "WTT_POST_SECONDARY_CLEAN"."VISA_TYPE_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."NATION_OF_CITIZENSHIP" = "WTT_POST_SECONDARY_CLEAN"."NATION_OF_CITIZENSHIP_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."NATION_OF_BIRTH" = "WTT_POST_SECONDARY_CLEAN"."NATION_OF_BIRTH_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."PRIMARY_DISABILITY" = "WTT_POST_SECONDARY_CLEAN"."PRIMARY_DISABILITY_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."LEGACY" = "WTT_POST_SECONDARY_CLEAN"."LEGACY_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."MARITAL_STATUS" = "WTT_POST_SECONDARY_CLEAN"."MARITAL_STATUS_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."RELIGION" = "WTT_POST_SECONDARY_CLEAN"."RELIGION_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."VETERAN_TYPE" = "WTT_POST_SECONDARY_CLEAN"."VETERAN_TYPE_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."VETERAN_CATEGORY" = "WTT_POST_SECONDARY_CLEAN"."VETERAN_CATEGORY_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."USER_ATTRIBUTE_01" = "WTT_POST_SECONDARY_CLEAN"."DEMO_USER_ATTRIBUTE_01_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."USER_ATTRIBUTE_02" = "WTT_POST_SECONDARY_CLEAN"."DEMO_USER_ATTRIBUTE_02_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."USER_ATTRIBUTE_03" = "WTT_POST_SECONDARY_CLEAN"."DEMO_USER_ATTRIBUTE_03_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."USER_ATTRIBUTE_04" = "WTT_POST_SECONDARY_CLEAN"."DEMO_USER_ATTRIBUTE_04_WV" )  AND
  ( "WDT_DEMOGRAPHIC"."USER_ATTRIBUTE_05" = "WTT_POST_SECONDARY_CLEAN"."DEMO_USER_ATTRIBUTE_05_WV" )  AND
  ( "WDT_POST_SECONDARY_SCHOOL"."POST_SECONDARY_DEGREE" = "WTT_POST_SECONDARY_CLEAN"."POST_SECONDARY_DEGREE_WV" )  AND
  ( "WDT_POST_SECONDARY_SCHOOL"."POST_SECONDARY_AWD_CATEGORY" = "WTT_POST_SECONDARY_CLEAN"."POST_SECONDARY_AWD_CATEGORY_WV" )  AND
  ( "WDT_POST_SECONDARY_SCHOOL"."POST_SECONDARY_MAJOR" = "WTT_POST_SECONDARY_CLEAN"."POST_SECONDARY_MAJOR_WV" )  AND
  ( "WDT_POST_SECONDARY_SCHOOL"."POST_SECONDARY_GPA_RANGE" = "WTT_POST_SECONDARY_CLEAN"."POST_SECONDARY_GPA_RANGE_WV" )  AND
  ( "WDT_POST_SECONDARY_SCHOOL"."TRANSFER_CREDIT_RANGE" = "WTT_POST_SECONDARY_CLEAN"."TRANSFER_CREDIT_RANGE_WV" )  AND
  ( "WDT_POST_SECONDARY_SCHOOL"."USER_ATTRIBUTE_01" = "WTT_POST_SECONDARY_CLEAN"."PSECS_USER_ATTRIBUTE_01_WV" )  AND
  ( "WDT_POST_SECONDARY_SCHOOL"."USER_ATTRIBUTE_02" = "WTT_POST_SECONDARY_CLEAN"."PSECS_USER_ATTRIBUTE_02_WV" )  AND
  ( "WDT_POST_SECONDARY_SCHOOL"."USER_ATTRIBUTE_03" = "WTT_POST_SECONDARY_CLEAN"."PSECS_USER_ATTRIBUTE_03_WV" )  AND
  ( "WDT_POST_SECONDARY_SCHOOL"."USER_ATTRIBUTE_04" = "WTT_POST_SECONDARY_CLEAN"."PSECS_USER_ATTRIBUTE_04_WV" )  AND
  ( "WDT_POST_SECONDARY_SCHOOL"."USER_ATTRIBUTE_05" = "WTT_POST_SECONDARY_CLEAN"."PSECS_USER_ATTRIBUTE_05_WV" )  AND
  ( "WTT_POST_SECONDARY_CLEAN"."TWO_OR_MORE_IND_WV" = "WDT_DEMOGRAPHIC"."TWO_OR_MORE_IND" )  AND
  ( "WTT_POST_SECONDARY_CLEAN"."NON_RESIDENT_IND_WV" = "WDT_DEMOGRAPHIC"."NON_RESIDENT_IND" )  AND
  ( "WTT_POST_SECONDARY_CLEAN"."RACE_ETHNICITY_UNKNOWN_IND_WV"= "WDT_DEMOGRAPHIC"."RACE_ETHNICITY_UNKNOWN_IND" )  AND
  ( "WTT_POST_SECONDARY_CLEAN"."RACE_ETHNICITY_CONFIRM_IND_WV" = "WDT_DEMOGRAPHIC"."RACE_ETHNICITY_CONFIRM_IND" )  AND
  ( "WTT_POST_SECONDARY_CLEAN"."MINORITY_IND_WV"  =  "WDT_DEMOGRAPHIC"."MINORITY_IND"/* OPERATOR JOINER JOIN CONDITION */ ) 