


BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ACAD_OUTCOME_14"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ACAD_OUTCOME_14"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsByGroup(99,JOB_NUM,''LOAD_EDW_ACADEMIC_OUTCOME'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2014'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ACAD_OUTCOME_14"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ACAD_OUTCOME_09"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ACAD_OUTCOME_09"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsByGroup(99,JOB_NUM,''LOAD_EDW_ACADEMIC_OUTCOME'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2009'');
END; ');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ACAD_OUTCOME_09"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ACAD_OUTCOME_10"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ACAD_OUTCOME_10"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsByGroup(99,JOB_NUM,''LOAD_EDW_ACADEMIC_OUTCOME'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2010'');
END; ');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ACAD_OUTCOME_10"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ACAD_OUTCOME_11"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ACAD_OUTCOME_11"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsByGroup(99,JOB_NUM,''LOAD_EDW_ACADEMIC_OUTCOME'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2011'');
END; ');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ACAD_OUTCOME_11"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ACAD_OUTCOME_12"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ACAD_OUTCOME_12"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsByGroup(99,JOB_NUM,''LOAD_EDW_ACADEMIC_OUTCOME'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2012'');
END; ');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ACAD_OUTCOME_12"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ACAD_OUTCOME_13"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ACAD_OUTCOME_13"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsByGroup(99,JOB_NUM,''LOAD_EDW_ACADEMIC_OUTCOME'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2013'');
END; ');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ACAD_OUTCOME_13"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ACAD_OUTCOME_14"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ACAD_OUTCOME_14"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsByGroup(99,JOB_NUM,''LOAD_EDW_ACADEMIC_OUTCOME'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2014'');
END; ');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ACAD_OUTCOME_14"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ACAD_OUTCOME_15"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ACAD_OUTCOME_15"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsByGroup(99,JOB_NUM,''LOAD_EDW_ACADEMIC_OUTCOME'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2015'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ACAD_OUTCOME_15"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADMIS_APP_09"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADMIS_APP_09"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_ADMISSIONS_APPLICATION-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2009'');
END; ');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADMIS_APP_09"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADMIS_APP_10"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADMIS_APP_10"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_ADMISSIONS_APPLICATION-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2010'');
END; ');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADMIS_APP_10"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADMIS_APP_11"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADMIS_APP_11"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_ADMISSIONS_APPLICATION-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2011'');
END; ');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADMIS_APP_11"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADMIS_APP_12"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADMIS_APP_12"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_ADMISSIONS_APPLICATION-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2012'');
END; ');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADMIS_APP_12"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADMIS_APP_13"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADMIS_APP_13"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_ADMISSIONS_APPLICATION-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2013'');
END; ');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADMIS_APP_13"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADMIS_APP_14"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADMIS_APP_14"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_ADMISSIONS_APPLICATION-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2014'');
END; ');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADMIS_APP_14"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADMIS_APP_15"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADMIS_APP_15"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_ADMISSIONS_APPLICATION-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2015'');
END; ');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADMIS_APP_15"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADMIS_APP_16"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADMIS_APP_16"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_ADMISSIONS_APPLICATION-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2016'');
END; ');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADMIS_APP_16"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADMIS_APP_17"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADMIS_APP_17"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_ADMISSIONS_APPLICATION-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2017'');
END; ');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADMIS_APP_17"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADVISOR_09"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADVISOR_09"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_ADVISOR-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2009'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADVISOR_09"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADVISOR_10"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADVISOR_10"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_ADVISOR-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2010'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADVISOR_10"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADVISOR_11"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADVISOR_11"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_ADVISOR-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2011'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADVISOR_11"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADVISOR_12"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADVISOR_12"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_ADVISOR-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2012'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADVISOR_12"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADVISOR_13"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADVISOR_13"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_ADVISOR-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2013'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADVISOR_13"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADVISOR_14"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADVISOR_14"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_ADVISOR-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2014'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADVISOR_14"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADVISOR_15"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADVISOR_15"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_ADVISOR-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2015'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_ADVISOR_15"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_COURSE_SECT_09"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_COURSE_SECT_09"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_COURSE_SECTION-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2009'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_COURSE_SECT_09"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_COURSE_SECT_10"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_COURSE_SECT_10"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_COURSE_SECTION-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2010'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_COURSE_SECT_10"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_COURSE_SECT_11"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_COURSE_SECT_11"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_COURSE_SECTION-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2011'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_COURSE_SECT_11"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_COURSE_SECT_12"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_COURSE_SECT_12"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_COURSE_SECTION-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2012'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_COURSE_SECT_12"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_COURSE_SECT_13"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_COURSE_SECT_13"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_COURSE_SECTION-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2013'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_COURSE_SECT_13"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_COURSE_SECT_14"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_COURSE_SECT_14"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_COURSE_SECTION-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2014'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_COURSE_SECT_14"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_COURSE_SECT_15"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_COURSE_SECT_15"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_COURSE_SECTION-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2015'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_COURSE_SECT_15"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_CRS_INST_09"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_CRS_INST_09"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_CRS_INST-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2009'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_CRS_INST_09"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_CRS_INST_10"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_CRS_INST_10"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_CRS_INST-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2010'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_CRS_INST_10"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_CRS_INST_11"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_CRS_INST_11"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_CRS_INST-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2011'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_CRS_INST_11"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_CRS_INST_12"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_CRS_INST_12"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_CRS_INST-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2012'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_CRS_INST_12"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_CRS_INST_13"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_CRS_INST_13"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_CRS_INST-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2013'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_CRS_INST_13"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_CRS_INST_14"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_CRS_INST_14"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_CRS_INST-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2014'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_CRS_INST_14"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_CRS_INST_15"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_CRS_INST_15"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_CRS_INST-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2015'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_CRS_INST_15"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_FINAID_AGG_09"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_FINAID_AGG_09"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_ADMS_FINAID_AGG'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2009'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_FINAID_AGG_09"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_FINAID_AGG_10"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_FINAID_AGG_10"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_ADMS_FINAID_AGG'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2010'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_FINAID_AGG_10"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_FINAID_AGG_11"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_FINAID_AGG_11"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_ADMS_FINAID_AGG'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2011'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_FINAID_AGG_11"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_FINAID_AGG_12"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_FINAID_AGG_12"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_ADMS_FINAID_AGG'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2012'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_FINAID_AGG_12"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_FINAID_AGG_13"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_FINAID_AGG_13"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_ADMS_FINAID_AGG'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2013'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_FINAID_AGG_13"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_FINAID_AGG_14"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_FINAID_AGG_14"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_ADMS_FINAID_AGG'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2014'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_FINAID_AGG_14"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_FINAID_AGG_15"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_FINAID_AGG_15"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_ADMS_FINAID_AGG'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2015'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_FINAID_AGG_15"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_GRADE_CHANGE_09"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_GRADE_CHANGE_09"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_GRADE_CHANGE-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2009'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_GRADE_CHANGE_09"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_GRADE_CHANGE_10"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_GRADE_CHANGE_10"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_GRADE_CHANGE-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2010'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_GRADE_CHANGE_10"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_GRADE_CHANGE_11"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_GRADE_CHANGE_11"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_GRADE_CHANGE-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2011'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_GRADE_CHANGE_11"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_GRADE_CHANGE_12"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_GRADE_CHANGE_12"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_GRADE_CHANGE-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2012'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_GRADE_CHANGE_12"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_GRADE_CHANGE_13"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_GRADE_CHANGE_13"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_GRADE_CHANGE-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2013'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_GRADE_CHANGE_13"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_GRADE_CHANGE_14"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_GRADE_CHANGE_14"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_GRADE_CHANGE-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2014'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_GRADE_CHANGE_14"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_GRADE_CHANGE_15"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_GRADE_CHANGE_15"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_GRADE_CHANGE-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2015'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_GRADE_CHANGE_15"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_MEETING_TIME_09"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_MEETING_TIME_09"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_MEETING_TIME-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2009'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_MEETING_TIME_09"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_MEETING_TIME_10"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_MEETING_TIME_10"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_MEETING_TIME-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2010'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_MEETING_TIME_10"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_MEETING_TIME_11"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_MEETING_TIME_11"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_MEETING_TIME-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2011'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_MEETING_TIME_11"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_MEETING_TIME_12"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_MEETING_TIME_12"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_MEETING_TIME-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2012'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_MEETING_TIME_12"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_MEETING_TIME_13"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_MEETING_TIME_13"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_MEETING_TIME-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2013'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_MEETING_TIME_13"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_MEETING_TIME_14"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_MEETING_TIME_14"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_MEETING_TIME-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2014'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_MEETING_TIME_14"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_MEETING_TIME_15"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_MEETING_TIME_15"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_MEETING_TIME-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2015'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_MEETING_TIME_15"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_SEC_SCHOOL_SUBJ"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_SEC_SCHOOL_SUBJ"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
   mgkmap.P_RunETLMapSlotsByGroup(99,JOB_NUM,''LOAD_EDW_SEC_SCHL_SUBJECT'',NULL, ''PROCESS_IND_IN = L'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_SEC_SCHOOL_SUBJ"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUDENT_09"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUDENT_09"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_STUDENT_STAR-P'',NULL, ''PROCESS_IND_IN = L| BMI_CREATE_IND_IN = CREATE_BMI-PARALLEL| ACADEMIC_YEAR_IN = 2009'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUDENT_09"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUDENT_10"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUDENT_10"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_STUDENT_STAR-P'',NULL, ''PROCESS_IND_IN = L| BMI_CREATE_IND_IN = CREATE_BMI-PARALLEL| ACADEMIC_YEAR_IN = 2010'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUDENT_10"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUDENT_11"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUDENT_11"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_STUDENT_STAR-P'',NULL, ''PROCESS_IND_IN = L| BMI_CREATE_IND_IN = CREATE_BMI-PARALLEL| ACADEMIC_YEAR_IN = 2011'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUDENT_11"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUDENT_12"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUDENT_12"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_STUDENT_STAR-P'',NULL, ''PROCESS_IND_IN = L| BMI_CREATE_IND_IN = CREATE_BMI-PARALLEL| ACADEMIC_YEAR_IN = 2012'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUDENT_12"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUDENT_13"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUDENT_13"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_STUDENT_STAR-P'',NULL, ''PROCESS_IND_IN = L| BMI_CREATE_IND_IN = CREATE_BMI-PARALLEL| ACADEMIC_YEAR_IN = 2013'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUDENT_13"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUDENT_14"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUDENT_14"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_STUDENT_STAR-P'',NULL, ''PROCESS_IND_IN = L| BMI_CREATE_IND_IN = CREATE_BMI-PARALLEL| ACADEMIC_YEAR_IN = 2014'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUDENT_14"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUDENT_15"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUDENT_15"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_STUDENT_STAR-P'',NULL, ''PROCESS_IND_IN = L| BMI_CREATE_IND_IN = CREATE_BMI-PARALLEL| ACADEMIC_YEAR_IN = 2015'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUDENT_15"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_COURSE_09"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_COURSE_09"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_STUDENT_COURSE-P'',NULL, ''PROCESS_IND_IN = L| BMI_CREATE_IND_IN = CREATE_BMI-PARALLEL| ACADEMIC_YEAR_IN = 2009'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_COURSE_09"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_COURSE_10"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_COURSE_10"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_STUDENT_COURSE-P'',NULL, ''PROCESS_IND_IN = L| BMI_CREATE_IND_IN = CREATE_BMI-PARALLEL| ACADEMIC_YEAR_IN = 2010'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_COURSE_10"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_COURSE_11"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_COURSE_11"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_STUDENT_COURSE-P'',NULL, ''PROCESS_IND_IN = L| BMI_CREATE_IND_IN = CREATE_BMI-PARALLEL| ACADEMIC_YEAR_IN = 2011'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_COURSE_11"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_COURSE_12"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_COURSE_12"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_STUDENT_COURSE-P'',NULL, ''PROCESS_IND_IN = L| BMI_CREATE_IND_IN = CREATE_BMI-PARALLEL| ACADEMIC_YEAR_IN = 2012'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_COURSE_12"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_COURSE_13"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_COURSE_13"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_STUDENT_COURSE-P'',NULL, ''PROCESS_IND_IN = L| BMI_CREATE_IND_IN = CREATE_BMI-PARALLEL| ACADEMIC_YEAR_IN = 2013'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_COURSE_13"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_COURSE_14"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_COURSE_14"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_STUDENT_COURSE-P'',NULL, ''PROCESS_IND_IN = L| BMI_CREATE_IND_IN = CREATE_BMI-PARALLEL| ACADEMIC_YEAR_IN = 2014'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_COURSE_14"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_COURSE_15"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_COURSE_15"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_STUDENT_COURSE-P'',NULL, ''PROCESS_IND_IN = L| BMI_CREATE_IND_IN = CREATE_BMI-PARALLEL| ACADEMIC_YEAR_IN = 2015'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_COURSE_15"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_CRSE_ATR_09"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_CRSE_ATR_09"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_STUDENT_COURSE_ATTRIBUTE-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2009'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_CRSE_ATR_09"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_CRSE_ATR_10"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_CRSE_ATR_10"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_STUDENT_COURSE_ATTRIBUTE-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2010'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_CRSE_ATR_10"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_CRSE_ATR_11"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_CRSE_ATR_11"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_STUDENT_COURSE_ATTRIBUTE-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2011'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_CRSE_ATR_11"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_CRSE_ATR_12"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_CRSE_ATR_12"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_STUDENT_COURSE_ATTRIBUTE-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2012'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_CRSE_ATR_12"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_CRSE_ATR_13"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_CRSE_ATR_13"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_STUDENT_COURSE_ATTRIBUTE-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2013'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_CRSE_ATR_13"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_CRSE_ATR_14"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_CRSE_ATR_14"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_STUDENT_COURSE_ATTRIBUTE-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2014'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_CRSE_ATR_14"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_CRSE_ATR_15"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_CRSE_ATR_15"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsForGroups(99,JOB_NUM,''LOAD_EDW_STUDENT_COURSE_ATTRIBUTE-P'',NULL, ''PROCESS_IND_IN = L| ACADEMIC_YEAR_IN = 2015'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_CRSE_ATR_15"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_ENG_AGG"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_ENG_AGG"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsByGroup(99,JOB_NUM,''LOAD_EDW_STUD_ENG_AGG_INSERT'',NULL, ''PROCESS_IND_IN = L'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_ENG_AGG"');
END;

BEGIN
DBMS_SCHEDULER.DISABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_PROG_AGG"',
force=>TRUE);
DBMS_SCHEDULER.SET_ATTRIBUTE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_PROG_AGG"',
attribute=>'PROGRAM_ACTION',
value=>'DECLARE
   JOB_NUM   NUMBER;
BEGIN
   SELECT sys.jobseq.nextval INTO JOB_NUM from dual;
mgkmap.P_RunETLMapSlotsByGroup(99,JOB_NUM,''LOAD_EDW_STUD_PROG_AGG_INSERT'',NULL, ''PROCESS_IND_IN = L'');
END;');
DBMS_SCHEDULER.ENABLE(
name=>'"IA_ADMIN"."CCCS_LOAD_EDW_STUD_PROG_AGG"');
END;
